---
title: "intra/inter-tables"
output:
  word_document: default
  html_document: default
date: "2022-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(flextable)
library(extrafont)
library(scales)
library(forcats)
```

```{r, fig.height=4.5, fig.width=7}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```





```{r, fig.height=4.5, fig.width=7}
intra_data_all <- read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\PAPER_1\\intra_ICC_all.xlsx")
```

```{r}
intra_data_all <- intra_data_all %>% 
  rename(rater="coder",
         lower="Lower CI",
         upper="Upper CI")
```


```{r}
flextable(intra_data_all) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption(" ") %>% 
  fit_to_width(7.5) %>% 
  autofit()
```


```{r, fig.height=4.5, fig.width=7}
phase_one_intra <- intra_data_all %>% 
  filter(phase == "phase 1")

flextable(phase_one_intra) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Phase 1 ICC statistics for IntraRR") %>% 
  fit_to_width(7.5) %>% 
  autofit()



phase_one_intra %>% 
  ggplot(aes(x=fct_rev(measure), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(rater))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Phase 1 IntraRR, per individual rater",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")
```


```{r, fig.height=4.5, fig.width=7}
phase_three_intra <- intra_data_all %>% 
  filter(phase == "phase 3")

flextable(phase_three_intra) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Phase 3 ICC statistics for IntraRR") %>% 
  fit_to_width(7.5) %>% 
  autofit()

phase_three_intra %>% 
  ggplot(aes(x=fct_rev(measure), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(rater))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Phase 3 IntraRR, per individual rater",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")
```


```{r, fig.height=4.5, fig.width=7}
inter_data_all <- read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\PAPER_1\\inter_ICC_all.xlsx")

inter_data_all <- inter_data_all %>% 
  rename(lower="Lower CI",
         upper="Upper CI")
```


```{r}
flextable(inter_data_all) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption(" ") %>% 
  fit_to_width(7.5) %>% 
  autofit()
```


```{r, fig.height=4.5, fig.width=5}
phase_one_inter <- inter_data_all %>% 
  filter(phase == "phase 1")

flextable(phase_one_inter) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Phase 1 ICC statistics for InterRR") %>% 
  fit_to_width(7.5) %>% 
  autofit()

phase_one_inter %>% 
  ggplot(aes(x=fct_rev(measure), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  #facet_grid(cols=vars(rater))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Phase 1 InterRR, for all raters",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")
```



```{r, fig.height=4.5, fig.width=5}
phase_two_inter <- inter_data_all %>% 
  filter(phase == "phase 2")

flextable(phase_two_inter) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Phase 2 ICC statistics for InterRR") %>% 
  fit_to_width(7.5) %>% 
  autofit()

phase_two_inter %>% 
  ggplot(aes(x=fct_rev(measure), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  #facet_grid(cols=vars(rater))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Phase 2 InterRR, for all raters",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")
```


```{r, fig.height=4.5, fig.width=5}
phase_three_inter <- inter_data_all %>% 
  filter(phase == "phase 3")

flextable(phase_three_inter) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Phase 3 ICC statistics for InterRR") %>% 
  fit_to_width(7.5) %>% 
  autofit()

phase_three_inter %>% 
  ggplot(aes(x=fct_rev(measure), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  #facet_grid(cols=vars(rater))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Phase 3 InterRR, for all raters",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")
```


```{r, fig.height=4.5, fig.width=7}
rater_a_data <- intra_data_all %>% 
  filter(rater == "A")

flextable(rater_a_data) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Rater A ICC statistics for IntraRR, Phases 1 and 3") %>% 
  fit_to_width(7.5) %>% 
  autofit()

rater_a_data$phase <- recode_factor(rater_a_data$phase, 
                                    'phase 1' = "Phase 1",
                                    'phase 3' = "Phase 3")

rater_a_data %>% 
  ggplot(aes(x=fct_reorder(measure, ICC), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater A IntraRR, Phases 1 and 3",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")

rater_a_data$intraRR <- as.factor(ifelse(rater_a_data$ICC < 0.5, 'Poor',
                                    ifelse(rater_a_data$ICC < 0.75, 'Moderate',
                                    ifelse(rater_a_data$ICC < 0.9, 'Good',
                                    ifelse(rater_a_data$ICC < 1, 'Excellent')))))


  
rater_a_data %>% 
  ggplot(aes(x=intraRR, label=scales::percent(prop.table(stat(count)))))+
  geom_histogram(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater A IntraRR, Phases 1 and 3",
       subtitle="Comparison of reliabilities",
       x="IntraRR",
       y="Count")
```

```{r, fig.height=4.5, fig.width=7}
rater_b_data <- intra_data_all %>% 
  filter(rater == "B")

flextable(rater_b_data) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Rater B ICC statistics for IntraRR, Phases 1 and 3") %>% 
  fit_to_width(7.5) %>% 
  autofit()

rater_b_data$phase <- recode_factor(rater_b_data$phase, 
                                    'phase 1' = "Phase 1",
                                    'phase 3' = "Phase 3")

rater_b_data %>% 
  ggplot(aes(x=fct_reorder(measure, ICC), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater B IntraRR, Phases 1 and 3",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")

rater_b_data$intraRR <- as.factor(ifelse(rater_b_data$ICC < 0.5, 'Poor',
                                    ifelse(rater_b_data$ICC < 0.75, 'Moderate',
                                    ifelse(rater_b_data$ICC < 0.9, 'Good',
                                    ifelse(rater_b_data$ICC < 1, 'Excellent')))))


  
rater_b_data %>% 
  ggplot(aes(x=intraRR, label=scales::percent(prop.table(stat(count)))))+
  geom_histogram(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater B IntraRR, Phases 1 and 3",
       subtitle="Comparison of reliabilities",
       x="IntraRR",
       y="Count")
```


```{r, fig.height=4.5, fig.width=7}
rater_c_data <- intra_data_all %>% 
  filter(rater == "C")

flextable(rater_c_data) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Rater C ICC statistics for IntraRR, Phases 1 and 3") %>% 
  fit_to_width(7.5) %>% 
  autofit()

rater_c_data$phase <- recode_factor(rater_c_data$phase, 
                                    'phase 1' = "Phase 1",
                                    'phase 3' = "Phase 3")

rater_c_data %>% 
  ggplot(aes(x=fct_reorder(measure, ICC), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater C IntraRR, Phases 1 and 3",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")

rater_c_data$intraRR <- as.factor(ifelse(rater_c_data$ICC < 0.5, 'Poor',
                                    ifelse(rater_c_data$ICC < 0.75, 'Moderate',
                                    ifelse(rater_c_data$ICC < 0.9, 'Good',
                                    ifelse(rater_c_data$ICC < 1, 'Excellent')))))


  
rater_c_data %>% 
  ggplot(aes(x=intraRR, label=scales::percent(prop.table(stat(count)))))+
  geom_histogram(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater C IntraRR, Phases 1 and 3",
       subtitle="Comparison of reliabilities",
       x="IntraRR",
       y="Count")
```


```{r, fig.height=4.5, fig.width=7}
rater_d_data <- intra_data_all %>% 
  filter(rater == "D")

flextable(rater_d_data) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Rater D ICC statistics for IntraRR, Phases 1 and 3") %>% 
  fit_to_width(7.5) %>% 
  autofit()

rater_d_data$phase <- recode_factor(rater_d_data$phase, 
                                    'phase 1' = "Phase 1",
                                    'phase 3' = "Phase 3")

rater_d_data %>% 
  ggplot(aes(x=fct_reorder(measure, ICC), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater D IntraRR, Phases 1 and 3",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")

rater_d_data$intraRR <- as.factor(ifelse(rater_d_data$ICC < 0.5, 'Poor',
                                    ifelse(rater_d_data$ICC < 0.75, 'Moderate',
                                    ifelse(rater_d_data$ICC < 0.9, 'Good',
                                    ifelse(rater_d_data$ICC < 1, 'Excellent')))))


  
rater_d_data %>% 
  ggplot(aes(x=intraRR, label=scales::percent(prop.table(stat(count)))))+
  geom_histogram(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="Rater D IntraRR, Phases 1 and 3",
       subtitle="Comparison of reliabilities",
       x="IntraRR",
       y="Count")
```



```{r, fig.height=4.5, fig.width=7}
inter_data_all$phase <- recode_factor(inter_data_all$phase, 
                                    'phase 1' = "Phase 1",
                                    'phase 2' = "Phase 2",
                                    'phase 3' = "Phase 3")


inter_data_all %>% 
  ggplot(aes(x=fct_reorder(measure, ICC), y=ICC, ymin=lower, ymax=upper))+
  geom_pointrange()+
  geom_hline(yintercept = c(0.5, 0.75, 0.9), linetype=2)+
  coord_flip(ylim = c(0, 1))+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="InterRR at Phases 1, 2, and 3",
       subtitle="ICC reliability limits indicated by dashed lines",
       x="3D Measurement Abbreviation",
       y="ICC with 95% Confidence Interval")

inter_data_all$interRR <- as.factor(ifelse(inter_data_all$ICC < 0.5, 'Poor',
                                    ifelse(inter_data_all$ICC < 0.75, 'Moderate',
                                    ifelse(inter_data_all$ICC < 0.9, 'Good',
                                    ifelse(inter_data_all$ICC < 1, 'Excellent')))))


  
inter_data_all %>% 
  ggplot(aes(x=interRR, label=scales::percent(prop.table(stat(count)))))+
  geom_histogram(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  facet_grid(cols=vars(phase))+
  theme_bw()+
  theme(text=element_text(family= "Times New Roman"))+
  labs(title="InterRR at Phases 1, 2, and 3",
       subtitle="Comparison of reliabilities",
       x="InterRR",
       y="Count")
```




