---
title: "data exploration"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(readr)
library(knitr)
library(kableExtra)
library(officer)
library(flextable)
library(extrafont)
```

```{r}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}
#times new roman ggplots
#library(remotes)
#remotes::install_version("Rttf2pt1", version = "1.3.8")
#font_import(paths = NULL, recursive = TRUE, prompt = TRUE,pattern = NULL)
#loadfonts(device = "win")
```


```{r}
#load(file="headscan_full")
#headscan_full <- read_csv("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\headscan_full.csv")
#is.data.frame(headscan_full)
#str(headscan_full)
headscan_full <- read_xlsx("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\headscan_full.xlsx")
```



```{r} 
age_sumstats <- headscan_full %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = percentile(age, 0.05, na.rm=TRUE),
            percent25th = percentile(age, 0.25, na.rm=TRUE),
            percent50th = percentile(age, 0.50, na.rm=TRUE),
            percent75th = percentile(age, 0.75, na.rm=TRUE),
            percent95th = percentile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

age_sumstats <- age_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#HTML Table           
#age_sumstats %>% 
  #kbl(caption = "Age SumStats") %>% 
  #kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)

#Size 12 Table TNR
flextable(age_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats")

#Autofit Width Table TNR
flextable(age_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats") %>% 
  autofit() %>% 
  fit_to_width(7.5)
```


```{r} 
raceage_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = percentile(age, 0.05, na.rm=TRUE),
            percent25th = percentile(age, 0.25, na.rm=TRUE),
            percent50th = percentile(age, 0.50, na.rm=TRUE),
            percent75th = percentile(age, 0.75, na.rm=TRUE),
            percent95th = percentile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

raceage_sumstats <- raceage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))
   
#HTML Table         
#raceage_sumstats %>% 
  #kbl(caption = "Age SumStats by Race/Ethnicity") %>% 
  #kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)

#Size 12 Table TNR
flextable(raceage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats by Race/Ethnicity") %>% 
  set_header_labels(values = list(race_eth = "Race/Ethnicity"))

#Autofit Width Table TNR
flextable(raceage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats by Race/Ethnicity") %>% 
  autofit() %>% 
  fit_to_width(7.5) %>% 
  set_header_labels(values = list(race_eth = "Race/Ethnicity"))
```


```{r}
genderage_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = percentile(age, 0.05, na.rm=TRUE),
            percent25th = percentile(age, 0.25, na.rm=TRUE),
            percent50th = percentile(age, 0.50, na.rm=TRUE),
            percent75th = percentile(age, 0.75, na.rm=TRUE),
            percent95th = percentile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

genderage_sumstats <- genderage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#HTML Table
#genderage_sumstats %>% 
  #kbl(caption = "Age SumStats by Gender") %>% 
  #kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)

#Size 12 Table TNR
flextable(genderage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats by Gender") %>% 
  set_header_labels(values = list(gender = "Gender"))

#Autofit Width Table TNR
flextable(genderage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats by Gender") %>% 
  autofit() %>% 
  fit_to_width(7.5) %>% 
  set_header_labels(values = list(gender = "Gender"))


```


```{r}
agegroup_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = percentile(age, 0.05, na.rm=TRUE),
            percent25th = percentile(age, 0.25, na.rm=TRUE),
            percent50th = percentile(age, 0.50, na.rm=TRUE),
            percent75th = percentile(age, 0.75, na.rm=TRUE),
            percent95th = percentile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

agegroup_sumstats <- agegroup_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))
   
#HTML Table         
#agegroup_sumstats %>% 
  #kbl(caption = "Age SumStats by Age Group") %>% 
  #kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)

#Size 12 Table TNR
flextable(agegroup_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats by Age Group")%>% 
  set_header_labels(values = list(age_group = "Age Group"))

#Autofit Width Table TNR
flextable(agegroup_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Age SumStats by Age Group") %>% 
  autofit() %>% 
  fit_to_width(7.5) %>%
  set_header_labels(values = list(age_group = "Age Group"))
```

```{r}
#explore race_eth, frequency of each

```

```{r}
#explore gender, frequency of each
```












PLOTS






```{r, fig.width= 6.5, fig.height=3.5}
ggplot(data=headscan_full, aes(x= age, fill=gender))+
  theme(text=element_text(family= "Times New Roman"))+
  scale_fill_grey(na.value="gray90")+
  geom_histogram(binwidth = 3)+
  labs(title="Headscan Sample Demographics: Age",
       subtitle="sorted by Race/Ethnicity, color by Gender",
       y="Count (variable scale per group)",
       x="Age",
       fill="Gender")+
  facet_wrap(~race_eth, scales="free_y")+
  scale_y_continuous(breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1)))))+
  geom_vline(xintercept = 37, color="red", linetype= "dashed")+
  geom_vline(xintercept = 55, color="red", linetype= "dashed")
  
```

```{r}
#ggplot(data=headscan_full)+
  #geom_histogram(binwidth=2, aes(x=age, fill=race_eth))+
  #scale_fill_grey()+
  #labs(title= "Demographics of Headscan Sample",
       #subtitle = "Data collected by Human Solutions",
       #fill= "Ethnicity",
       #y="Count",
       #x="Age")
```
```{r}
#ggplot(data=headscan_full)+
  #geom_boxplot(aes(x=race_eth, y=age, fill=gender))+
  #scale_fill_grey()+
  #theme(axis.text.x = element_text(angle = 45))
```