---
title: "imputing"
output:
  word_document: default
  html_document: default
date: "2022-09-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(flextable)
library(readxl)
library(writexl)
library(extrafont)
library(missMDA)
library(psych)
library(arsenal)
```

```{r table-function}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}

headscan_full1<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\headscan_full1.xlsx")

headscan_full1  <- column_to_rownames(headscan_full1,'ID')

headscan_num <- select_if(headscan_full1, is.numeric)
headscan_num <- subset(headscan_num, select= -age)
str(headscan_num)
```




```{r}
summary(headscan_num)
headscan_stats <- describe(headscan_num)


headscan_stats$na <- 2016 - headscan_stats$n
headscan_stats <- rownames_to_column(headscan_stats, "measure")
```


```{r}
AA_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(AA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(AA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(AA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(AA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(AA_C, 0.95, na.rm=TRUE))
AA_C_sum$measure <- "AA_C"


BGl_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(BGl_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BGl_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BGl_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BGl_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BGl_C, 0.95, na.rm=TRUE))
BGl_C_sum$measure <- "BGl_C"

BiW_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(BiW_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_C, 0.95, na.rm=TRUE))
BiW_C_sum$measure <- "BiW_C"

BiW_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(BiW_L, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_L, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_L, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_L, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_L, 0.95, na.rm=TRUE))
BiW_L_sum$measure <- "BiW_L"

ChCh_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(ChCh_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ChCh_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ChCh_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ChCh_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ChCh_C, 0.95, na.rm=TRUE))
ChCh_C_sum$measure <- "ChCh_C"

GoSub_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(GoSub_C, 0.05, na.rm=TRUE),
            percent25th = quantile(GoSub_C, 0.25, na.rm=TRUE),
            percent50th = quantile(GoSub_C, 0.50, na.rm=TRUE),
            percent75th = quantile(GoSub_C, 0.75, na.rm=TRUE),
            percent95th = quantile(GoSub_C, 0.95, na.rm=TRUE))
GoSub_C_sum$measure <- "GoSub_C"

NRB_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(NRB_L, 0.05, na.rm=TRUE),
            percent25th = quantile(NRB_L, 0.25, na.rm=TRUE),
            percent50th = quantile(NRB_L, 0.50, na.rm=TRUE),
            percent75th = quantile(NRB_L, 0.75, na.rm=TRUE),
            percent95th = quantile(NRB_L, 0.95, na.rm=TRUE))
NRB_L_sum$measure <- "NRB_L"

ProA_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(ProA_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_L, 0.95, na.rm=TRUE))
ProA_L_sum$measure <- "ProA_L"

ProA_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(ProA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_C, 0.95, na.rm=TRUE))
ProA_C_sum$measure <- "ProA_C"

ProS_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(ProS_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_C, 0.95, na.rm=TRUE))
ProS_C_sum$measure <- "ProS_C"

ProS_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(ProS_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_L, 0.95, na.rm=TRUE))
ProS_L_sum$measure <- "ProS_L"

SelP_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SelP_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_C, 0.95, na.rm=TRUE))
SelP_C_sum$measure <- "SelP_C"

SelP_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SelP_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_L, 0.95, na.rm=TRUE))
SelP_L_sum$measure <- "SelP_L"

SelDH_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SelDH_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelDH_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelDH_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelDH_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelDH_C, 0.95, na.rm=TRUE))
SelDH_C_sum$measure <- "SelDH_C"

SelM_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SelM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelM_L, 0.95, na.rm=TRUE))
SelM_L_sum$measure <- "SelM_L"

SnasM_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SnasM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_C, 0.95, na.rm=TRUE))
SnasM_C_sum$measure <- "SnasM_C"

SmanM_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SmanM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SmanM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SmanM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SmanM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SmanM_C, 0.95, na.rm=TRUE))
SmanM_C_sum$measure <- "SmanM_C"

SmanM_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SmanM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SmanM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SmanM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SmanM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SmanM_L, 0.95, na.rm=TRUE))
SmanM_L_sum$measure <- "SmanM_L"

SnasM_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(SnasM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_L, 0.95, na.rm=TRUE))
SnasM_L_sum$measure <- "SnasM_L"

TrHO_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrHO_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrHO_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrHO_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrHO_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrHO_C, 0.95, na.rm=TRUE))
TrHO_C_sum$measure <- "TrHO_C"

TrEJ_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrEJ_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrEJ_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrEJ_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrEJ_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrEJ_C, 0.95, na.rm=TRUE))
TrEJ_C_sum$measure <- "TrEJ_C"

TrGo_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrGo_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrGo_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrGo_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrGo_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrGo_C, 0.95, na.rm=TRUE))
TrGo_C_sum$measure <- "TrGo_C"

TrSel_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrSel_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSel_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSel_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSel_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSel_C, 0.95, na.rm=TRUE))
TrSel_C_sum$measure <- "TrSel_C"

TrSman_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrSman_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSman_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSman_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSman_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSman_C, 0.95, na.rm=TRUE))
TrSman_C_sum$measure <- "TrSman_C"

TrSnas_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrSnas_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSnas_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSnas_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSnas_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSnas_C, 0.95, na.rm=TRUE))
TrSnas_C_sum$measure <- "TrSnas_C"

TrTr_C_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrTr_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_C, 0.95, na.rm=TRUE))
TrTr_C_sum$measure <- "TrTr_C"

TrTr_L_sum <- headscan_num %>% 
  summarise(percent5th = quantile(TrTr_L, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_L, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_L, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_L, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_L, 0.95, na.rm=TRUE))
TrTr_L_sum$measure <- "TrTr_L"
```


```{r}
quantile_data <- rbind(AA_C_sum, BGl_C_sum, BiW_L_sum, BiW_C_sum, ChCh_C_sum,
                       GoSub_C_sum, NRB_L_sum, ProA_L_sum, ProA_C_sum, ProS_C_sum,
                       ProS_L_sum, SelP_C_sum, SelP_L_sum, SelDH_C_sum, SelM_L_sum,
                       SnasM_C_sum, SmanM_C_sum, SmanM_L_sum, SnasM_L_sum, TrHO_C_sum,
                       TrEJ_C_sum, TrGo_C_sum, TrSel_C_sum, TrSman_C_sum, TrSnas_C_sum,
                       TrTr_C_sum, TrTr_L_sum)
```

```{r}

headscan_stats$mdn <- headscan_stats$median

headscan_stats <- headscan_stats[c(1,3,15,9,10,4,16,5,14)]

headscan_stats <- full_join(headscan_stats, quantile_data, by="measure")

headscan_stats <- headscan_stats %>% 
  mutate(across(where(is.numeric), round, 2))
```


```{r}


#Autofit Width Table TNR
flextable(headscan_stats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Non-imputed SumStats (mm)") %>% 
  fit_to_width(7.5) 
```
Imputing data!!!

```{r}

imputed <- imputePCA(headscan_num, ncp=2)
imputed_data <- as.data.frame(imputed$completeObs)
imputed_data <- round(imputed_data, 0)
```



```{r}

imputed_stats <- describe(imputed_data)


imputed_stats$na <- 2016 - imputed_stats$n
imputed_stats <- rownames_to_column(imputed_stats, "measure")
```


```{r}
AA_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(AA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(AA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(AA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(AA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(AA_C, 0.95, na.rm=TRUE))
AA_C_sum1$measure <- "AA_C"


BGl_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(BGl_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BGl_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BGl_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BGl_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BGl_C, 0.95, na.rm=TRUE))
BGl_C_sum1$measure <- "BGl_C"

BiW_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(BiW_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_C, 0.95, na.rm=TRUE))
BiW_C_sum1$measure <- "BiW_C"

BiW_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(BiW_L, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_L, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_L, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_L, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_L, 0.95, na.rm=TRUE))
BiW_L_sum1$measure <- "BiW_L"

ChCh_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(ChCh_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ChCh_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ChCh_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ChCh_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ChCh_C, 0.95, na.rm=TRUE))
ChCh_C_sum1$measure <- "ChCh_C"

GoSub_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(GoSub_C, 0.05, na.rm=TRUE),
            percent25th = quantile(GoSub_C, 0.25, na.rm=TRUE),
            percent50th = quantile(GoSub_C, 0.50, na.rm=TRUE),
            percent75th = quantile(GoSub_C, 0.75, na.rm=TRUE),
            percent95th = quantile(GoSub_C, 0.95, na.rm=TRUE))
GoSub_C_sum1$measure <- "GoSub_C"

NRB_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(NRB_L, 0.05, na.rm=TRUE),
            percent25th = quantile(NRB_L, 0.25, na.rm=TRUE),
            percent50th = quantile(NRB_L, 0.50, na.rm=TRUE),
            percent75th = quantile(NRB_L, 0.75, na.rm=TRUE),
            percent95th = quantile(NRB_L, 0.95, na.rm=TRUE))
NRB_L_sum1$measure <- "NRB_L"

ProA_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(ProA_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_L, 0.95, na.rm=TRUE))
ProA_L_sum1$measure <- "ProA_L"

ProA_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(ProA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_C, 0.95, na.rm=TRUE))
ProA_C_sum1$measure <- "ProA_C"

ProS_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(ProS_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_C, 0.95, na.rm=TRUE))
ProS_C_sum1$measure <- "ProS_C"

ProS_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(ProS_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_L, 0.95, na.rm=TRUE))
ProS_L_sum1$measure <- "ProS_L"

SelP_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SelP_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_C, 0.95, na.rm=TRUE))
SelP_C_sum1$measure <- "SelP_C"

SelP_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SelP_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_L, 0.95, na.rm=TRUE))
SelP_L_sum1$measure <- "SelP_L"

SelDH_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SelDH_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelDH_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelDH_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelDH_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelDH_C, 0.95, na.rm=TRUE))
SelDH_C_sum1$measure <- "SelDH_C"

SelM_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SelM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelM_L, 0.95, na.rm=TRUE))
SelM_L_sum1$measure <- "SelM_L"

SnasM_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SnasM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_C, 0.95, na.rm=TRUE))
SnasM_C_sum1$measure <- "SnasM_C"

SmanM_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SmanM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SmanM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SmanM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SmanM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SmanM_C, 0.95, na.rm=TRUE))
SmanM_C_sum1$measure <- "SmanM_C"

SmanM_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SmanM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SmanM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SmanM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SmanM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SmanM_L, 0.95, na.rm=TRUE))
SmanM_L_sum1$measure <- "SmanM_L"

SnasM_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(SnasM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_L, 0.95, na.rm=TRUE))
SnasM_L_sum1$measure <- "SnasM_L"

TrHO_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrHO_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrHO_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrHO_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrHO_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrHO_C, 0.95, na.rm=TRUE))
TrHO_C_sum1$measure <- "TrHO_C"

TrEJ_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrEJ_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrEJ_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrEJ_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrEJ_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrEJ_C, 0.95, na.rm=TRUE))
TrEJ_C_sum1$measure <- "TrEJ_C"

TrGo_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrGo_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrGo_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrGo_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrGo_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrGo_C, 0.95, na.rm=TRUE))
TrGo_C_sum1$measure <- "TrGo_C"

TrSel_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrSel_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSel_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSel_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSel_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSel_C, 0.95, na.rm=TRUE))
TrSel_C_sum1$measure <- "TrSel_C"

TrSman_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrSman_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSman_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSman_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSman_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSman_C, 0.95, na.rm=TRUE))
TrSman_C_sum1$measure <- "TrSman_C"

TrSnas_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrSnas_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSnas_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSnas_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSnas_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSnas_C, 0.95, na.rm=TRUE))
TrSnas_C_sum1$measure <- "TrSnas_C"

TrTr_C_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrTr_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_C, 0.95, na.rm=TRUE))
TrTr_C_sum1$measure <- "TrTr_C"

TrTr_L_sum1 <- imputed_data %>% 
  summarise(percent5th = quantile(TrTr_L, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_L, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_L, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_L, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_L, 0.95, na.rm=TRUE))
TrTr_L_sum1$measure <- "TrTr_L"
```


```{r}
quantile_data <- rbind(AA_C_sum1, BGl_C_sum1, BiW_L_sum1, BiW_C_sum1, ChCh_C_sum1,
                       GoSub_C_sum1, NRB_L_sum1, ProA_L_sum1, ProA_C_sum1, ProS_C_sum1,
                       ProS_L_sum1, SelP_C_sum1, SelP_L_sum1, SelDH_C_sum1, SelM_L_sum1,
                       SnasM_C_sum1, SmanM_C_sum1, SmanM_L_sum1, SnasM_L_sum1, TrHO_C_sum1,
                       TrEJ_C_sum1, TrGo_C_sum1, TrSel_C_sum1, TrSman_C_sum1, TrSnas_C_sum1,
                       TrTr_C_sum1, TrTr_L_sum1)
```

```{r}

imputed_stats$mdn <- imputed_stats$median

imputed_stats <- imputed_stats[c(1,3,15,9,10,4,16,5,14)]

imputed_stats <- full_join(imputed_stats, quantile_data, by="measure")

imputed_stats <- imputed_stats %>% 
  mutate(across(where(is.numeric), round, 2))
```


```{r}


#Autofit Width Table TNR
flextable(imputed_stats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Imputed SumStats (mm)") %>% 
  fit_to_width(7.5) 
```


```{r}
diff <- headscan_stats

diff <- diff %>% 
  rename(original_n=n,
         original_na=na,
         original_min=min,
         original_max=max,
         original_mean=mean,
         original_mdn=mdn,
         original_sd=sd,
         original_se=se,
         original5th=percent5th,
         original25th=percent25th,
         original50th=percent50th,
         original75th=percent75th,
         original95th=percent95th)

diff$imputed_n <- imputed_stats$n
diff$imputed_na <- imputed_stats$na
diff$imputed_min <- imputed_stats$min
diff$imputed_max <- imputed_stats$max
diff$imputed_mean <- imputed_stats$mean
diff$imputed_mdn <- imputed_stats$mdn
diff$imputed_sd <- imputed_stats$sd
diff$imputed_se <- imputed_stats$se
diff$imputed5th <- imputed_stats$percent5th
diff$imputed25th <- imputed_stats$percent25th
diff$imputed50th <- imputed_stats$percent50th
diff$imputed75th <- imputed_stats$percent75th
diff$imputed95th <- imputed_stats$percent95th


diff <- diff %>% 
  mutate(across(where(is.numeric), round, 2))

diff$n_diff <- diff$imputed_n - diff$original_n
diff$na_diff <- diff$imputed_na - diff$original_na
diff$min_diff <- diff$imputed_min - diff$original_min
diff$max_diff <- diff$imputed_max - diff$original_max
diff$mean_diff <- diff$imputed_mean - diff$original_mean
diff$mdn_diff <- diff$imputed_mdn - diff$original_mdn
diff$sd_diff <- diff$imputed_sd - diff$original_sd
diff$se_diff <- diff$imputed_se - diff$original_se
diff$diff_5th <- diff$imputed5th - diff$original5th
diff$diff_25th <- diff$imputed25th - diff$original25th
diff$diff_50th <- diff$imputed50th - diff$original50th
diff$diff_75th <- diff$imputed75th - diff$original75th
diff$diff_95th <- diff$imputed95th - diff$original95th

diff <- diff[c(1, 28:40)]

str(diff)
```

```{r}

#Autofit Width Table TNR
flextable(diff) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Differences (mm) Between Imputed and Original SumStats") %>% 
  fit_to_width(7.5) 
```

```{r}
diff_selected <- diff[c(1,3,4,6,7,11,13,15,19,24,26,27),]

#Autofit Width Table TNR
flextable(diff_selected) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Differences (mm) Between Imputed and Original SumStats") %>% 
  fit_to_width(7.5) 
```



```{r}
headscan_full1 <- rownames_to_column(headscan_full1, "ID")
imputed_data <- rownames_to_column(imputed_data, "ID")

headscan_demographics <- headscan_full1[c(1,29:33)]

imputed_data <- full_join(imputed_data, headscan_demographics, by="ID")

write_xlsx(imputed_data, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\imputed_data.xlsx")
```

```{r}

```

