---
title: "PCA demographics"
output: html_document
date: "2022-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(readxl)
library(flextable)
library(extrafont)
library(forcats)
```

```{r table-function}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```


```{r}
PCAdata_full<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\PCAdata_full.xlsx")

PCAdata_full$gender<-as.factor(PCAdata_full$gender)
PCAdata_full$race_eth<-as.factor(PCAdata_full$race_eth)
PCAdata_full$age_group<-as.factor(PCAdata_full$age_group)


str(PCAdata_full)
```




```{r}
PCAdata_full %>% 
  ggplot(aes(x=fct_infreq(race_eth), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Race/Ethnicity Frequency",
       subtitle="PCA data",
       y="Count",
       x="Race/Ethnicity")
```



```{r}
PCAdata_full %>% 
  ggplot(aes(x=fct_infreq(gender), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Gender Frequency",
       subtitle="PCA data",
       y="Count",
       x="Gender")
```



```{r}
PCAdata_full %>% 
  ggplot(aes(x=fct_infreq(age_group), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Age Group Frequency",
       subtitle="PCA data",
       y="Count",
       x="Age Group")
```