---
title: "PCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(flextable)
library(readxl)
library(extrafont)
library(forcats)
library(writexl)
library(ggfortify)
```

```{r table-function}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}
#remove identifiers and demographic data

headscan_full1<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\headscan_full.xlsx")

headscan_full1$AA_C <- headscan_full1$AA_C *10
headscan_full1$BGl_C <- headscan_full1$BGl_C * 10
headscan_full1$BiW_C <- headscan_full1$BiW_C *10
headscan_full1$BiW_L <- headscan_full1$BiW_L *10
headscan_full1$ChCh_C <- headscan_full1$ChCh_C *10
headscan_full1$GoSub_C <- headscan_full1$GoSub_C *10
headscan_full1$NRB_L <- headscan_full1$NRB_L *10
headscan_full1$ProA_L <- headscan_full1$ProA_L *10
headscan_full1$ProA_C <- headscan_full1$ProA_C *10
headscan_full1$ProS_C <- headscan_full1$ProS_C *10
headscan_full1$ProS_L <- headscan_full1$ProS_L *10
headscan_full1$SelP_C <- headscan_full1$SelP_C *10
headscan_full1$SelP_L <- headscan_full1$SelP_L *10
headscan_full1$SelDH_C <- headscan_full1$SelDH_C *10
headscan_full1$SelM_L <- headscan_full1$SelM_L *10
headscan_full1$SnasM_C <- headscan_full1$SnasM_C *10
headscan_full1$SmanM_C <- headscan_full1$SmanM_C *10
headscan_full1$SmanM_L <- headscan_full1$SmanM_L *10
headscan_full1$SnasM_L <- headscan_full1$SnasM_L *10
headscan_full1$TrHO_C <- headscan_full1$TrHO_C *10
headscan_full1$TrEJ_C <- headscan_full1$TrEJ_C *10
headscan_full1$TrGo_C <- headscan_full1$TrGo_C *10
headscan_full1$TrSel_C <- headscan_full1$TrSel_C *10
headscan_full1$TrSman_C <- headscan_full1$TrSman_C *10
headscan_full1$TrSnas_C <- headscan_full1$TrSnas_C *10
headscan_full1$TrTr_C <- headscan_full1$TrTr_C *10
headscan_full1$TrTr_L <- headscan_full1$TrTr_L *10

str(headscan_full1)
```


```{r}
PCAdata_num <- headscan_full1[c(1,2,4,5,7,8,12,14,16,17,25,27,28)]

PCAdata_full <- headscan_full1[c(1,2,4,5,7,8,12,14,16,17,25,27,28,31,32,33)]
```


```{r}
measureNAs <- read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\measureNAs.xlsx")

PCA_NAs <- slice(measureNAs, c(1,3,4,6,7,11,13,15,16,24,26,27))

#Size 12 Table TNR
flextable(PCA_NAs) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("NA values for PCA Measurement Locations, total 891 NA values") %>% 
  autofit() %>% 
  set_header_labels(values = list(measure_name = "Measurement Location",
                                  measureNAprops = "Proportion of NA values",
                                  measureNAsums = "Count of NA values"))
```



```{r}
PCAdata_num <- PCAdata_num %>% drop_na()

str(PCAdata_num)
```




```{r}
PCAdata_full <- left_join(PCAdata_num, PCAdata_full, by= "ID")

PCAdata_full <- PCAdata_full %>% 
  rename(AA_C = "AA_C.x",
         BiW_C = "BiW_C.x",
         BiW_L = "BiW_L.x",
         GoSub_C = "GoSub_C.x",
         NRB_L = "NRB_L.x",
         ProS_L = "ProS_L.x",
         SelP_L = "SelP_L.x",
         SelM_L = "SelM_L.x",
         SnasM_C = "SnasM_C.x",
         TrSman_C = "TrSman_C.x",
         TrTr_C = "TrTr_C.x",
         TrTr_L = "TrTr_L.x")

PCAdata_full <- PCAdata_full[-c(14:25)]
```


```{r}
PCAdata_num <- PCAdata_num[-c(1)]
PCAdata_full <- PCAdata_full[-c(1)]
```


```{r}
#https://www.statology.org/principal-components-analysis-in-r/

#calculate principal components
pca_res <- prcomp(PCAdata_num, scale=TRUE)

#reverse the signs (R calculates eigenvectors in negative direction)
pca_res$rotation <- -1*pca_res$rotation

#display PCs
pca_res$rotation
```


```{r}
var_explained = pca_res$sdev^2 / sum(pca_res$sdev^2)

var_explained_total <- var_explained
```


```{r, fig.width=5, fig.height=4}
qplot(c(1:12), var_explained) + 
  geom_line() + 
  xlab("Principal Component") + 
  ylab("Variance Explained (proportion)") +
  ggtitle("Scree Plot") +
  ylim(0, 1) +
  scale_x_discrete(limits=c("PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10","PC11","PC12")) 
```


```{r}

#making plot axis match the ggplot versions in PCA2.Rmd!!! 
#compare to PCAdata_full1 pc1 and pc2 columns (should be same sign, here times 100)
pca_res$x <- pca_res$x * 100
pca_res$x[,1] <- pca_res$x[,1] * -1
#pca_res$x <- pca_res$x[,2] * 100

pca_res$x
```


#https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html

```{r}
autoplot(pca_res, data=PCAdata_full, colour="race_eth")
```
```{r}
autoplot(pca_res, data=PCAdata_full, colour="race_eth",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)
```
arrows close together=higher correlation


```{r}
autoplot(pca_res, data=PCAdata_full, colour="gender")
```

```{r}
autoplot(pca_res, data=PCAdata_full, colour="gender",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)
```


```{r}
autoplot(pca_res, data=PCAdata_full, colour="age_group")
```


```{r}
autoplot(pca_res, data=PCAdata_full, colour="age_group",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)
```


```{r}
write_xlsx(PCAdata_full, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\PCAdata_full.xlsx")
```

