---
title: "PCA2"
output: html_document
date: "2022-08-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

WOULD NOT RECOMMEND USING THIS! Scale is different from other PCA graphs on PCA.Rmd

```{r}
library(FactoMineR)
library(factoextra)
library(tidyverse)
library(MASS)
library(reshape2)
library(cowplot)
library(flextable)
library(readxl)
library(extrafont)
library(forcats)
library(writexl)
library(ggfortify)
library(fauxnaif)
```


```{r}
PCAdata_full<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\PCAdata_full.xlsx")

str(PCAdata_full)
```


```{r}
#https://tem11010.github.io/Plotting-PCAs/

PCAdata_full1 <-  PCAdata_full %>% filter (AA_C > 0, BiW_C > 0, BiW_L > 0, GoSub_C > 0, 
                                           NRB_L > 0, ProS_L > 0, SelP_L > 0, SelM_L > 0, 
                                           SnasM_C > 0, TrSman_C > 0, TrTr_C > 0, TrTr_L > 0)

# log price

# center and scale the data
for (i in 1:length(colnames(PCAdata_full1))){
  
  if (is.numeric(PCAdata_full1[, i])==TRUE)
    
    PCAdata_full1[, i] <- as.numeric(scale(PCAdata_full1[, i]))
  
  else
    
    PCAdata_full1[, i] <- PCAdata_full1[, i]
  
}
```


```{r}
pca1 <- PCA(PCAdata_full1[ ,c("AA_C", "BiW_C", "BiW_L", "GoSub_C", "NRB_L", "ProS_L", "SelP_L", 
                             "SelM_L", "SnasM_C", "TrSman_C", "TrTr_C", "TrTr_L")])

summary(pca1)
```

```{r}
PCAdata_full1$pc1 <- pca1$ind$coord[, 1] # indexing the first column

PCAdata_full1$pc2 <- pca1$ind$coord[, 2]  # indexing the second column


```

```{r}
pca.vars <- pca1$var$coord %>% data.frame

pca.vars$vars <- rownames(pca.vars)

pca.vars.m <- melt(pca.vars, id.vars = "vars")
```

```{r}
#circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
  #r = diameter / 2
  #tt <- seq(0,2*pi,length.out = npoints)
  #xx <- center[1] + r * cos(tt)
  #yy <- center[2] + r * sin(tt)
  #return(data.frame(x = xx, y = yy))
#}

#circ <- circleFun(c(0,0),2,npoints = 500)
```


```{r}
PCAdata_full1$race_eth <- as.factor(PCAdata_full1$race_eth)
PCAdata_full1$gender <- as.factor(PCAdata_full1$gender)
PCAdata_full1$age_group <- as.factor(PCAdata_full1$age_group)
```


```{r}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2)) +
  geom_point()+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)")
```

```{r}
#checking to make sure this matches plot in PCA.Rmd
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) +
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Race/Ethnicities PCA plot")
```

```{r}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Race/Ethnicities PCA plot")
```
Need a plot with just Asian, Black, LatinX, and white

```{r}
PCAdata_race_eth <- PCAdata_full1 %>% 
  recode_factor(PCAdata_full1$race_eth, 'AIAN'= "Other",
                'NHOPI' = "Other",
                'PTNS' = "Other")

PCAdata_race_eth1 <- PCAdata_race_eth %>% 
  mutate(race_eth = na_if_in(race_eth, c("white", "LatinX")))

str(PCAdata_race_eth$race_eth)
```
```{r}
ggplot(data = PCAdata_race_eth, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth, na.rm=TRUE), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title="Four Most Common Race/Ethnicities PCA plot")
```
Just Asian and Black?

```{r}
PCAdata_race_eth1 <- PCAdata_race_eth %>% 
  mutate(race_eth = na_if_in(race_eth, c("white", "LatinX")))
```
```{r}
ggplot(data = PCAdata_race_eth1, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth, na.rm=TRUE), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title="Black and Asian Race/Ethnicities PCA plot")
```


```{r}
#checking to make sure this matches plot in PCA.Rmd
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) +
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)")
```


```{r}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = gender), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)")
```
Need plot with just Male and Female 




```{r}
#checking to make sure this matches plot in PCA.Rmd
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = age_group)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) +
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)")
```


```{r}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = age_group)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = age_group), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)")
```
Need plot with just 18-36 and 37-54