---
title: "running-MANOVA"
output: html_document
date: "2022-09-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(readxl)
library(officer)
library(flextable)
library(extrafont)
library(writexl)
library(rstatix)
library(corrr)
library(corrplot)
library(car)
library(heplots)
```

```{r}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}

chosen_nona1 <- read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chosen_nona1.xlsx")

variables <- cbind(chosen_nona1$AA_C, chosen_nona1$BiW_C, chosen_nona1$BiW_L, 
                   chosen_nona1$GoSub_C, chosen_nona1$NRB_L, chosen_nona1$ProS_L,
                   chosen_nona1$SelP_L, chosen_nona1$SelM_L, chosen_nona1$SnasM_C,
                   chosen_nona1$TrSman_C, chosen_nona1$TrTr_C, chosen_nona1$TrTr_L)

manova_out_nona <- manova(variables ~ gender+race_eth+age_group, data=chosen_nona1)

summary(manova_out_nona)
```

https://www.hindawi.com/journals/cmmm/2019/2173638/



