---
title: "summary stats SA1"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(flextable)
library(readxl)
```

```{r}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}
headscan_full<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\headscan_full.xlsx")
```

```{r}
#HTML Table format    
#AACrace_sumstats %>% 
  #kbl(caption = "Alare to Alare Contour SumStats by Race/Ethnicity") %>% 
  #kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)

```

```{r}
#exploring NA values for measurements
measureNAsums <- colSums(is.na(headscan_full))

measureNAprops <- colMeans(is.na(headscan_full))

measureNAprops1 <- as.data.frame(measureNAprops)
measureNAprops1 <- rownames_to_column(measureNAprops1, "measure_name")
measureNAprops1 <- measureNAprops1 %>% slice(-c(1, 29:33))

measureNAsums1 <- as.data.frame(measureNAsums)
measureNAsums1 <- rownames_to_column(measureNAsums1, "measure_name")
measureNAsums1 <- measureNAsums1 %>% slice(-c(1, 29:33))

measureNAs <- inner_join(measureNAprops1, measureNAsums1, by = "measure_name")

#Size 12 Table TNR
flextable(measureNAs) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("NA values for each Measurement Location") %>% 
  set_header_labels(values = list(measure_name = "Measurement Location",
                                  measureNAprops = "Proportion of NA values",
                                  measureNAsums = "Count of NA values"))

```
AA_C race/eth, gender, age group sumstats

```{r}
#AA_C race/eth sumstats
AA_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(AA_C, na.rm = TRUE),
            max = max(AA_C, na.rm = TRUE),
            mean = mean(AA_C, na.rm = TRUE),
            sd = sd(AA_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(AA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(AA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(AA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(AA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(AA_C, 0.95, na.rm=TRUE),
            na = sum(is.na(AA_C))) 

AA_Crace_sumstats <- AA_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(AA_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Alare to Alare Contour SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(AA_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Alare to Alare Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```

```{r}
#AA_C gender sumstats
AA_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(AA_C, na.rm = TRUE),
            max = max(AA_C, na.rm = TRUE),
            mean = mean(AA_C, na.rm = TRUE),
            sd = sd(AA_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(AA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(AA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(AA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(AA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(AA_C, 0.95, na.rm=TRUE),
            na = sum(is.na(AA_C)))

AA_Cgender_sumstats <- AA_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(AA_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Alare to Alare Contour SumStats by Gender") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(AA_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Alare to Alare Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```

```{r}
#AA_C age group sumstats
AA_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(AA_C, na.rm = TRUE),
            max = max(AA_C, na.rm = TRUE),
            mean = mean(AA_C, na.rm = TRUE),
            sd = sd(AA_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(AA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(AA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(AA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(AA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(AA_C, 0.95, na.rm=TRUE),
            na = sum(is.na(AA_C)))

AA_Cage_sumstats <- AA_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(AA_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Alare to Alare Contour SumStats by Gender") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(AA_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Alare to Alare Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```


BGl_C  race/eth, gender, age group sumstats

```{r}
#BGl_C race/eth sumstats
BGl_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(BGl_C, na.rm = TRUE),
            max = max(BGl_C, na.rm = TRUE),
            mean = mean(BGl_C, na.rm = TRUE),
            sd = sd(BGl_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BGl_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BGl_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BGl_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BGl_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BGl_C, 0.95, na.rm=TRUE),
            na = sum(is.na(BGl_C))) 

BGl_Crace_sumstats <- BGl_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(BGl_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Back of Head to Glabella Contour SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(BGl_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BGl_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Back of Head to Glabella Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BGl_C = "Alare/AlareCont"))
```

```{r}
#BGl_C gender sumstats
BGl_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(BGl_C, na.rm = TRUE),
            max = max(BGl_C, na.rm = TRUE),
            mean = mean(BGl_C, na.rm = TRUE),
            sd = sd(BGl_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BGl_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BGl_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BGl_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BGl_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BGl_C, 0.95, na.rm=TRUE),
            na = sum(is.na(BGl_C)))

BGl_Cgender_sumstats <- BGl_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(BGl_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Back of Head to Glabella Contour SumStats by Gender") 
#%>% set_header_labels(values = list(BGl_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BGl_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Back of Head to Glabella Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BGl_C = "Alare/AlareCont"))
```

```{r}
#BGl_C age group sumstats
BGl_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(BGl_C, na.rm = TRUE),
            max = max(BGl_C, na.rm = TRUE),
            mean = mean(BGl_C, na.rm = TRUE),
            sd = sd(BGl_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BGl_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BGl_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BGl_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BGl_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BGl_C, 0.95, na.rm=TRUE),
            na = sum(is.na(BGl_C)))

BGl_Cage_sumstats <- BGl_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(BGl_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Back of Head to Glabella Contour SumStats by Gender") 
#%>% set_header_labels(values = list(BGl_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BGl_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Back of Head to Glabella Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BGl_C = "Alare/AlareCont"))
```



BiW_L  

```{r}
#BiW_L race/eth sumstats
BiW_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(BiW_L, na.rm = TRUE),
            max = max(BiW_L, na.rm = TRUE),
            mean = mean(BiW_L, na.rm = TRUE),
            sd = sd(BiW_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BiW_L, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_L, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_L, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_L, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_L, 0.95, na.rm=TRUE),
            na = sum(is.na(BiW_L))) 

BiW_Lrace_sumstats <- BiW_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(BiW_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Linear SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(BiW_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BiW_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Linear SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BiW_L = "Alare/AlareCont"))
```

```{r}
#BiW_L gender sumstats
BiW_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(BiW_L, na.rm = TRUE),
            max = max(BiW_L, na.rm = TRUE),
            mean = mean(BiW_L, na.rm = TRUE),
            sd = sd(BiW_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BiW_L, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_L, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_L, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_L, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_L, 0.95, na.rm=TRUE),
            na = sum(is.na(BiW_L)))

BiW_Lgender_sumstats <- BiW_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(BiW_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Linear SumStats by Gender") 
#%>% set_header_labels(values = list(BiW_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BiW_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Linear SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BiW_L = "Alare/AlareCont"))
```

```{r}
#BiW_L age group sumstats
BiW_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(BiW_L, na.rm = TRUE),
            max = max(BiW_L, na.rm = TRUE),
            mean = mean(BiW_L, na.rm = TRUE),
            sd = sd(BiW_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BiW_L, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_L, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_L, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_L, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_L, 0.95, na.rm=TRUE),
            na = sum(is.na(BiW_L)))

BiW_Lage_sumstats <- BiW_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(BiW_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Linear SumStats by Gender") 
#%>% set_header_labels(values = list(BiW_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BiW_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Linear SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BiW_L = "Alare/AlareCont"))
```



BiW_C  

```{r}
#BiW_C race/eth sumstats
BiW_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(BiW_C, na.rm = TRUE),
            max = max(BiW_C, na.rm = TRUE),
            mean = mean(BiW_C, na.rm = TRUE),
            sd = sd(BiW_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BiW_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_C, 0.95, na.rm=TRUE),
            na = sum(is.na(BiW_C))) 

BiW_Crace_sumstats <- BiW_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(BiW_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Contour SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(BiW_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BiW_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BiW_C = "Alare/AlareCont"))
```

```{r}
#BiW_C gender sumstats
BiW_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(BiW_C, na.rm = TRUE),
            max = max(BiW_C, na.rm = TRUE),
            mean = mean(BiW_C, na.rm = TRUE),
            sd = sd(BiW_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BiW_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_C, 0.95, na.rm=TRUE),
            na = sum(is.na(BiW_C)))

BiW_Cgender_sumstats <- BiW_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(BiW_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Contour SumStats by Gender") 
#%>% set_header_labels(values = list(BiW_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BiW_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BiW_C = "Alare/AlareCont"))
```

```{r}
#BiW_C age group sumstats
BiW_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(BiW_C, na.rm = TRUE),
            max = max(BiW_C, na.rm = TRUE),
            mean = mean(BiW_C, na.rm = TRUE),
            sd = sd(BiW_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(BiW_C, 0.05, na.rm=TRUE),
            percent25th = quantile(BiW_C, 0.25, na.rm=TRUE),
            percent50th = quantile(BiW_C, 0.50, na.rm=TRUE),
            percent75th = quantile(BiW_C, 0.75, na.rm=TRUE),
            percent95th = quantile(BiW_C, 0.95, na.rm=TRUE),
            na = sum(is.na(BiW_C)))

BiW_Cage_sumstats <- BiW_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(BiW_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Contour SumStats by Gender") 
#%>% set_header_labels(values = list(BiW_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(BiW_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Bizygomatic Width Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(BiW_C = "Alare/AlareCont"))
```


ChCh_C  

```{r}
#ChCh_C race/eth sumstats
ChCh_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(ChCh_C, na.rm = TRUE),
            max = max(ChCh_C, na.rm = TRUE),
            mean = mean(ChCh_C, na.rm = TRUE),
            sd = sd(ChCh_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ChCh_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ChCh_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ChCh_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ChCh_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ChCh_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ChCh_C))) 

ChCh_Crace_sumstats <- ChCh_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ChCh_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Chellion Chellion Contour SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(ChCh_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ChCh_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Chellion Chellion Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ChCh_C = "Alare/AlareCont"))
```

```{r}
#ChCh_C gender sumstats
ChCh_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(ChCh_C, na.rm = TRUE),
            max = max(ChCh_C, na.rm = TRUE),
            mean = mean(ChCh_C, na.rm = TRUE),
            sd = sd(ChCh_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ChCh_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ChCh_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ChCh_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ChCh_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ChCh_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ChCh_C)))

ChCh_Cgender_sumstats <- ChCh_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(ChCh_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Chellion Chellion Contour SumStats by Gender") 
#%>% set_header_labels(values = list(ChCh_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ChCh_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Chellion Chellion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ChCh_C = "Alare/AlareCont"))
```

```{r}
#ChCh_C age group sumstats
ChCh_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(ChCh_C, na.rm = TRUE),
            max = max(ChCh_C, na.rm = TRUE),
            mean = mean(ChCh_C, na.rm = TRUE),
            sd = sd(ChCh_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ChCh_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ChCh_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ChCh_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ChCh_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ChCh_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ChCh_C)))

ChCh_Cage_sumstats <- ChCh_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ChCh_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Chellion Chellion Contour SumStats by Gender") 
#%>% set_header_labels(values = list(ChCh_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ChCh_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Chellion Chellion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ChCh_C = "Alare/AlareCont"))
```


GoSub_C  

```{r}
#GoSub_C race/eth sumstats
GoSub_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(GoSub_C, na.rm = TRUE),
            max = max(GoSub_C, na.rm = TRUE),
            mean = mean(GoSub_C, na.rm = TRUE),
            sd = sd(GoSub_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(GoSub_C, 0.05, na.rm=TRUE),
            percent25th = quantile(GoSub_C, 0.25, na.rm=TRUE),
            percent50th = quantile(GoSub_C, 0.50, na.rm=TRUE),
            percent75th = quantile(GoSub_C, 0.75, na.rm=TRUE),
            percent95th = quantile(GoSub_C, 0.95, na.rm=TRUE),
            na = sum(is.na(GoSub_C))) 

GoSub_Crace_sumstats <- GoSub_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(GoSub_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Gonion Submandibular Contour SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(GoSub_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(GoSub_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Gonion Submandibular Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(GoSub_C = "Alare/AlareCont"))
```

```{r}
#GoSub_C gender sumstats
GoSub_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(GoSub_C, na.rm = TRUE),
            max = max(GoSub_C, na.rm = TRUE),
            mean = mean(GoSub_C, na.rm = TRUE),
            sd = sd(GoSub_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(GoSub_C, 0.05, na.rm=TRUE),
            percent25th = quantile(GoSub_C, 0.25, na.rm=TRUE),
            percent50th = quantile(GoSub_C, 0.50, na.rm=TRUE),
            percent75th = quantile(GoSub_C, 0.75, na.rm=TRUE),
            percent95th = quantile(GoSub_C, 0.95, na.rm=TRUE),
            na = sum(is.na(GoSub_C)))

GoSub_Cgender_sumstats <- GoSub_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(GoSub_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Gonion Submandibular Contour SumStats by Gender") 
#%>% set_header_labels(values = list(GoSub_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(GoSub_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Gonion Submandibular Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(GoSub_C = "Alare/AlareCont"))
```

```{r}
#GoSub_C age group sumstats
GoSub_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(GoSub_C, na.rm = TRUE),
            max = max(GoSub_C, na.rm = TRUE),
            mean = mean(GoSub_C, na.rm = TRUE),
            sd = sd(GoSub_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(GoSub_C, 0.05, na.rm=TRUE),
            percent25th = quantile(GoSub_C, 0.25, na.rm=TRUE),
            percent50th = quantile(GoSub_C, 0.50, na.rm=TRUE),
            percent75th = quantile(GoSub_C, 0.75, na.rm=TRUE),
            percent95th = quantile(GoSub_C, 0.95, na.rm=TRUE),
            na = sum(is.na(GoSub_C)))

GoSub_Cage_sumstats <- GoSub_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(GoSub_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Gonion Submandibular Contour SumStats by Gender") 
#%>% set_header_labels(values = list(GoSub_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(GoSub_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Gonion Submandibular Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(GoSub_C = "Alare/AlareCont"))
```



NRB_L  

```{r}
#NRB_L race/eth sumstats
NRB_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(NRB_L, na.rm = TRUE),
            max = max(NRB_L, na.rm = TRUE),
            mean = mean(NRB_L, na.rm = TRUE),
            sd = sd(NRB_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(NRB_L, 0.05, na.rm=TRUE),
            percent25th = quantile(NRB_L, 0.25, na.rm=TRUE),
            percent50th = quantile(NRB_L, 0.50, na.rm=TRUE),
            percent75th = quantile(NRB_L, 0.75, na.rm=TRUE),
            percent95th = quantile(NRB_L, 0.95, na.rm=TRUE),
            na = sum(is.na(NRB_L))) 

NRB_Lrace_sumstats <- NRB_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(NRB_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Nasal Root Breadth SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(NRB_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(NRB_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Nasal Root Breadth SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(NRB_L = "Alare/AlareCont"))
```

```{r}
#NRB_L gender sumstats
NRB_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(NRB_L, na.rm = TRUE),
            max = max(NRB_L, na.rm = TRUE),
            mean = mean(NRB_L, na.rm = TRUE),
            sd = sd(NRB_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(NRB_L, 0.05, na.rm=TRUE),
            percent25th = quantile(NRB_L, 0.25, na.rm=TRUE),
            percent50th = quantile(NRB_L, 0.50, na.rm=TRUE),
            percent75th = quantile(NRB_L, 0.75, na.rm=TRUE),
            percent95th = quantile(NRB_L, 0.95, na.rm=TRUE),
            na = sum(is.na(NRB_L)))

NRB_Lgender_sumstats <- NRB_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(NRB_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Nasal Root Breadth SumStats by Gender") 
#%>% set_header_labels(values = list(NRB_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(NRB_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Nasal Root Breadth SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(NRB_L = "Alare/AlareCont"))
```

```{r}
#NRB_L age group sumstats
NRB_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(NRB_L, na.rm = TRUE),
            max = max(NRB_L, na.rm = TRUE),
            mean = mean(NRB_L, na.rm = TRUE),
            sd = sd(NRB_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(NRB_L, 0.05, na.rm=TRUE),
            percent25th = quantile(NRB_L, 0.25, na.rm=TRUE),
            percent50th = quantile(NRB_L, 0.50, na.rm=TRUE),
            percent75th = quantile(NRB_L, 0.75, na.rm=TRUE),
            percent95th = quantile(NRB_L, 0.95, na.rm=TRUE),
            na = sum(is.na(NRB_L)))

NRB_Lage_sumstats <- NRB_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(NRB_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Nasal Root Breadth SumStats by Gender") 
#%>% set_header_labels(values = list(NRB_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(NRB_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Nasal Root Breadth SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(NRB_L = "Alare/AlareCont"))
```





ProA_L  

```{r}
#ProA_L race/eth sumstats
ProA_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(ProA_L, na.rm = TRUE),
            max = max(ProA_L, na.rm = TRUE),
            mean = mean(ProA_L, na.rm = TRUE),
            sd = sd(ProA_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProA_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_L, 0.95, na.rm=TRUE),
            na = sum(is.na(ProA_L))) 

ProA_Lrace_sumstats <- ProA_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProA_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Length SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(ProA_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ProA_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Length SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ProA_L = "Alare/AlareCont"))
```

```{r}
#ProA_L gender sumstats
ProA_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(ProA_L, na.rm = TRUE),
            max = max(ProA_L, na.rm = TRUE),
            mean = mean(ProA_L, na.rm = TRUE),
            sd = sd(ProA_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProA_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_L, 0.95, na.rm=TRUE),
            na = sum(is.na(ProA_L)))

ProA_Lgender_sumstats <- ProA_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(ProA_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Length SumStats by Gender") 
#%>% set_header_labels(values = list(ProA_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ProA_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ProA_L = "Alare/AlareCont"))
```

```{r}
#ProA_L age group sumstats
ProA_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(ProA_L, na.rm = TRUE),
            max = max(ProA_L, na.rm = TRUE),
            mean = mean(ProA_L, na.rm = TRUE),
            sd = sd(ProA_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProA_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_L, 0.95, na.rm=TRUE),
            na = sum(is.na(ProA_L)))

ProA_Lage_sumstats <- ProA_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProA_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Length SumStats by Gender") 
#%>% set_header_labels(values = list(ProA_L = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ProA_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ProA_L = "Alare/AlareCont"))
```




ProA_C  

```{r}
#ProA_C race/eth sumstats
ProA_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(ProA_C, na.rm = TRUE),
            max = max(ProA_C, na.rm = TRUE),
            mean = mean(ProA_C, na.rm = TRUE),
            sd = sd(ProA_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ProA_C))) 

ProA_Crace_sumstats <- ProA_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProA_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(ProA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ProA_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(ProA_C = "Alare/AlareCont"))
```

```{r}
#ProA_C gender sumstats
ProA_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(ProA_C, na.rm = TRUE),
            max = max(ProA_C, na.rm = TRUE),
            mean = mean(ProA_C, na.rm = TRUE),
            sd = sd(ProA_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ProA_C)))

ProA_Cgender_sumstats <- ProA_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(ProA_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(ProA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ProA_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(ProA_C = "Alare/AlareCont"))
```

```{r}
#ProA_C age group sumstats
ProA_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(ProA_C, na.rm = TRUE),
            max = max(ProA_C, na.rm = TRUE),
            mean = mean(ProA_C, na.rm = TRUE),
            sd = sd(ProA_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProA_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProA_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProA_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProA_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProA_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ProA_C)))

ProA_Cage_sumstats <- ProA_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProA_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(ProA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(ProA_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Alare Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(ProA_C = "Alare/AlareCont"))
```



ProS_L  

```{r}
#ProS_L race/eth sumstats
ProS_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(ProS_L, na.rm = TRUE),
            max = max(ProS_L, na.rm = TRUE),
            mean = mean(ProS_L, na.rm = TRUE),
            sd = sd(ProS_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProS_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_L, 0.95, na.rm=TRUE),
            na = sum(is.na(ProS_L))) 

ProS_Lrace_sumstats <- ProS_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProS_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Length SumStats by Race/Ethnicity") 
#%>% set_header_labels(values = list(ProS_L = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(ProS_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Length SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ProS_L = "Subnasale/SubnasaleCont"))
```

```{r}
#ProS_L gender sumstats
ProS_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(ProS_L, na.rm = TRUE),
            max = max(ProS_L, na.rm = TRUE),
            mean = mean(ProS_L, na.rm = TRUE),
            sd = sd(ProS_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProS_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_L, 0.95, na.rm=TRUE),
            na = sum(is.na(ProS_L)))

ProS_Lgender_sumstats <- ProS_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(ProS_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Length SumStats by Gender") 
#%>% set_header_labels(values = list(ProS_L = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(ProS_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ProS_L = "Subnasale/SubnasaleCont"))
```

```{r}
#ProS_L age group sumstats
ProS_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(ProS_L, na.rm = TRUE),
            max = max(ProS_L, na.rm = TRUE),
            mean = mean(ProS_L, na.rm = TRUE),
            sd = sd(ProS_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProS_L, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_L, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_L, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_L, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_L, 0.95, na.rm=TRUE),
            na = sum(is.na(ProS_L)))

ProS_Lage_sumstats <- ProS_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProS_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Length SumStats by Gender") 
#%>% set_header_labels(values = list(ProS_L = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(ProS_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(ProS_L = "Subnasale/SubnasaleCont"))
```

ProS_C  

```{r}
#ProS_C race/eth sumstats
ProS_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(ProS_C, na.rm = TRUE),
            max = max(ProS_C, na.rm = TRUE),
            mean = mean(ProS_C, na.rm = TRUE),
            sd = sd(ProS_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProS_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ProS_C))) 

ProS_Crace_sumstats <- ProS_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProS_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(ProS_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(ProS_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(ProS_C = "Subnasale/SubnasaleCont"))
```

```{r}
#ProS_C gender sumstats
ProS_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(ProS_C, na.rm = TRUE),
            max = max(ProS_C, na.rm = TRUE),
            mean = mean(ProS_C, na.rm = TRUE),
            sd = sd(ProS_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProS_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ProS_C)))

ProS_Cgender_sumstats <- ProS_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(ProS_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(ProS_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(ProS_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(ProS_C = "Subnasale/SubnasaleCont"))
```

```{r}
#ProS_C age group sumstats
ProS_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(ProS_C, na.rm = TRUE),
            max = max(ProS_C, na.rm = TRUE),
            mean = mean(ProS_C, na.rm = TRUE),
            sd = sd(ProS_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(ProS_C, 0.05, na.rm=TRUE),
            percent25th = quantile(ProS_C, 0.25, na.rm=TRUE),
            percent50th = quantile(ProS_C, 0.50, na.rm=TRUE),
            percent75th = quantile(ProS_C, 0.75, na.rm=TRUE),
            percent95th = quantile(ProS_C, 0.95, na.rm=TRUE),
            na = sum(is.na(ProS_C)))

ProS_Cage_sumstats <- ProS_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(ProS_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(ProS_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(ProS_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Pronasale Subnasale Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(ProS_C = "Subnasale/SubnasaleCont"))
```



SelP_L  

```{r}
#SelP_L race/eth sumstats
SelP_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(SelP_L, na.rm = TRUE),
            max = max(SelP_L, na.rm = TRUE),
            mean = mean(SelP_L, na.rm = TRUE),
            sd = sd(SelP_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelP_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SelP_L))) 

SelP_Lrace_sumstats <- SelP_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelP_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Length SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(SelP_L = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelP_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Length SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelP_L = "Sellion/SellionCont"))
```

```{r}
#SelP_L gender sumstats
SelP_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(SelP_L, na.rm = TRUE),
            max = max(SelP_L, na.rm = TRUE),
            mean = mean(SelP_L, na.rm = TRUE),
            sd = sd(SelP_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelP_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SelP_L)))

SelP_Lgender_sumstats <- SelP_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(SelP_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Length SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelP_L = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelP_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelP_L = "Sellion/SellionCont"))
```

```{r}
#SelP_L age group sumstats
SelP_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(SelP_L, na.rm = TRUE),
            max = max(SelP_L, na.rm = TRUE),
            mean = mean(SelP_L, na.rm = TRUE),
            sd = sd(SelP_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelP_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SelP_L)))

SelP_Lage_sumstats <- SelP_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelP_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Length SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelP_L = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelP_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelP_L = "Sellion/SellionCont"))
```



SelP_C  

```{r}
#SelP_C race/eth sumstats
SelP_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(SelP_C, na.rm = TRUE),
            max = max(SelP_C, na.rm = TRUE),
            mean = mean(SelP_C, na.rm = TRUE),
            sd = sd(SelP_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelP_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SelP_C))) 

SelP_Crace_sumstats <- SelP_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelP_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(SelP_C = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelP_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelP_C = "Sellion/SellionCont"))
```

```{r}
#SelP_C gender sumstats
SelP_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(SelP_C, na.rm = TRUE),
            max = max(SelP_C, na.rm = TRUE),
            mean = mean(SelP_C, na.rm = TRUE),
            sd = sd(SelP_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelP_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SelP_C)))

SelP_Cgender_sumstats <- SelP_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(SelP_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelP_C = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelP_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelP_C = "Sellion/SellionCont"))
```

```{r}
#SelP_C age group sumstats
SelP_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(SelP_C, na.rm = TRUE),
            max = max(SelP_C, na.rm = TRUE),
            mean = mean(SelP_C, na.rm = TRUE),
            sd = sd(SelP_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelP_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelP_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelP_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelP_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelP_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SelP_C)))

SelP_Cage_sumstats <- SelP_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelP_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelP_C = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelP_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Pronasale Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelP_C = "Sellion/SellionCont"))
```



SelDH_C  

```{r}
#SelDH_C race/eth sumstats
SelDH_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(SelDH_C, na.rm = TRUE),
            max = max(SelDH_C, na.rm = TRUE),
            mean = mean(SelDH_C, na.rm = TRUE),
            sd = sd(SelDH_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelDH_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelDH_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelDH_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelDH_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelDH_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SelDH_C))) 

SelDH_Crace_sumstats <- SelDH_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelDH_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Dorsal Hump Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(SelDH_C = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelDH_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Dorsal Hump Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelDH_C = "Sellion/SellionCont"))
```

```{r}
#SelDH_C gender sumstats
SelDH_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(SelDH_C, na.rm = TRUE),
            max = max(SelDH_C, na.rm = TRUE),
            mean = mean(SelDH_C, na.rm = TRUE),
            sd = sd(SelDH_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelDH_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelDH_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelDH_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelDH_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelDH_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SelDH_C)))

SelDH_Cgender_sumstats <- SelDH_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(SelDH_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Dorsal Hump Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelDH_C = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelDH_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Dorsal Hump Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelDH_C = "Sellion/SellionCont"))
```

```{r}
#SelDH_C age group sumstats
SelDH_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(SelDH_C, na.rm = TRUE),
            max = max(SelDH_C, na.rm = TRUE),
            mean = mean(SelDH_C, na.rm = TRUE),
            sd = sd(SelDH_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelDH_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SelDH_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SelDH_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SelDH_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SelDH_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SelDH_C)))

SelDH_Cage_sumstats <- SelDH_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelDH_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Dorsal Hump Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelDH_C = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelDH_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Dorsal Hump Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelDH_C = "Sellion/SellionCont"))
```



SelM_L  

```{r}
#SelM_L race/eth sumstats
SelM_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(SelM_L, na.rm = TRUE),
            max = max(SelM_L, na.rm = TRUE),
            mean = mean(SelM_L, na.rm = TRUE),
            sd = sd(SelM_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelM_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SelM_L))) 

SelM_Lrace_sumstats <- SelM_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelM_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Menton Length SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(SelM_L = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelM_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Menton Length SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelM_L = "Sellion/SellionCont"))
```

```{r}
#SelM_L gender sumstats
SelM_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(SelM_L, na.rm = TRUE),
            max = max(SelM_L, na.rm = TRUE),
            mean = mean(SelM_L, na.rm = TRUE),
            sd = sd(SelM_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelM_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SelM_L)))

SelM_Lgender_sumstats <- SelM_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(SelM_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Menton Length SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelM_L = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelM_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Menton Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelM_L = "Sellion/SellionCont"))
```

```{r}
#SelM_L age group sumstats
SelM_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(SelM_L, na.rm = TRUE),
            max = max(SelM_L, na.rm = TRUE),
            mean = mean(SelM_L, na.rm = TRUE),
            sd = sd(SelM_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SelM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SelM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SelM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SelM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SelM_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SelM_L)))

SelM_Lage_sumstats <- SelM_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SelM_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Menton Length SumStats by Gender") 
#%>% set_header_Cabels(values = list(SelM_L = "Sellion/SellionCont"))

#Autofit Width Table TNR
flextable(SelM_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Sellion to Menton Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SelM_L = "Sellion/SellionCont"))
```



SnasM_L  

```{r}
#SnasM_L race/eth sumstats
SnasM_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(SnasM_L, na.rm = TRUE),
            max = max(SnasM_L, na.rm = TRUE),
            mean = mean(SnasM_L, na.rm = TRUE),
            sd = sd(SnasM_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SnasM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SnasM_L))) 

SnasM_Lrace_sumstats <- SnasM_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SnasM_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Length SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(SnasM_L = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(SnasM_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Length SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SnasM_L = "Subnasale/SubnasaleCont"))
```

```{r}
#SnasM_L gender sumstats
SnasM_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(SnasM_L, na.rm = TRUE),
            max = max(SnasM_L, na.rm = TRUE),
            mean = mean(SnasM_L, na.rm = TRUE),
            sd = sd(SnasM_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SnasM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SnasM_L)))

SnasM_Lgender_sumstats <- SnasM_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(SnasM_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Length SumStats by Gender") 
#%>% set_header_Cabels(values = list(SnasM_L = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(SnasM_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SnasM_L = "Subnasale/SubnasaleCont"))
```

```{r}
#SnasM_L age group sumstats
SnasM_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(SnasM_L, na.rm = TRUE),
            max = max(SnasM_L, na.rm = TRUE),
            mean = mean(SnasM_L, na.rm = TRUE),
            sd = sd(SnasM_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SnasM_L, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_L, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_L, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_L, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_L, 0.95, na.rm=TRUE),
            na = sum(is.na(SnasM_L)))

SnasM_Lage_sumstats <- SnasM_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SnasM_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Length SumStats by Gender") 
#%>% set_header_Cabels(values = list(SnasM_L = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(SnasM_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Length SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SnasM_L = "Subnasale/SubnasaleCont"))
```



SnasM_C  

```{r}
#SnasM_C race/eth sumstats
SnasM_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(SnasM_C, na.rm = TRUE),
            max = max(SnasM_C, na.rm = TRUE),
            mean = mean(SnasM_C, na.rm = TRUE),
            sd = sd(SnasM_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SnasM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SnasM_C))) 

SnasM_Crace_sumstats <- SnasM_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SnasM_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(SnasM_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(SnasM_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SnasM_C = "Subnasale/SubnasaleCont"))
```

```{r}
#SnasM_C gender sumstats
SnasM_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(SnasM_C, na.rm = TRUE),
            max = max(SnasM_C, na.rm = TRUE),
            mean = mean(SnasM_C, na.rm = TRUE),
            sd = sd(SnasM_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SnasM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SnasM_C)))

SnasM_Cgender_sumstats <- SnasM_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(SnasM_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(SnasM_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(SnasM_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SnasM_C = "Subnasale/SubnasaleCont"))
```

```{r}
#SnasM_C age group sumstats
SnasM_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(SnasM_C, na.rm = TRUE),
            max = max(SnasM_C, na.rm = TRUE),
            mean = mean(SnasM_C, na.rm = TRUE),
            sd = sd(SnasM_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(SnasM_C, 0.05, na.rm=TRUE),
            percent25th = quantile(SnasM_C, 0.25, na.rm=TRUE),
            percent50th = quantile(SnasM_C, 0.50, na.rm=TRUE),
            percent75th = quantile(SnasM_C, 0.75, na.rm=TRUE),
            percent95th = quantile(SnasM_C, 0.95, na.rm=TRUE),
            na = sum(is.na(SnasM_C)))

SnasM_Cage_sumstats <- SnasM_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(SnasM_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(SnasM_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(SnasM_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Subnasale to Menton Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(SnasM_C = "Subnasale/SubnasaleCont"))
```



TrHO_C  

```{r}
#TrHO_C race/eth sumstats
TrHO_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrHO_C, na.rm = TRUE),
            max = max(TrHO_C, na.rm = TRUE),
            mean = mean(TrHO_C, na.rm = TRUE),
            sd = sd(TrHO_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrHO_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrHO_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrHO_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrHO_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrHO_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrHO_C))) 

TrHO_Crace_sumstats <- TrHO_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrHO_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Top of Head to Otobasion Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrHO_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrHO_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Top of Head to Otobasion Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrHO_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrHO_C gender sumstats
TrHO_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrHO_C, na.rm = TRUE),
            max = max(TrHO_C, na.rm = TRUE),
            mean = mean(TrHO_C, na.rm = TRUE),
            sd = sd(TrHO_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrHO_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrHO_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrHO_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrHO_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrHO_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrHO_C)))

TrHO_Cgender_sumstats <- TrHO_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrHO_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Top of Head to Otobasion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrHO_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrHO_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Top of Head to Otobasion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrHO_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrHO_C age group sumstats
TrHO_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrHO_C, na.rm = TRUE),
            max = max(TrHO_C, na.rm = TRUE),
            mean = mean(TrHO_C, na.rm = TRUE),
            sd = sd(TrHO_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrHO_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrHO_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrHO_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrHO_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrHO_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrHO_C)))

TrHO_Cage_sumstats <- TrHO_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrHO_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Top of Head to Otobasion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrHO_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrHO_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Top of Head to Otobasion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrHO_C = "Subnasale/SubnasaleCont"))
```



TrEJ_C  

```{r}
#TrEJ_C race/eth sumstats
TrEJ_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrEJ_C, na.rm = TRUE),
            max = max(TrEJ_C, na.rm = TRUE),
            mean = mean(TrEJ_C, na.rm = TRUE),
            sd = sd(TrEJ_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrEJ_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrEJ_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrEJ_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrEJ_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrEJ_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrEJ_C))) 

TrEJ_Crace_sumstats <- TrEJ_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrEJ_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Earlobe Juncture Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrEJ_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrEJ_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Earlobe Juncture Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrEJ_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrEJ_C gender sumstats
TrEJ_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrEJ_C, na.rm = TRUE),
            max = max(TrEJ_C, na.rm = TRUE),
            mean = mean(TrEJ_C, na.rm = TRUE),
            sd = sd(TrEJ_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrEJ_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrEJ_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrEJ_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrEJ_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrEJ_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrEJ_C)))

TrEJ_Cgender_sumstats <- TrEJ_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrEJ_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Earlobe Juncture Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrEJ_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrEJ_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Earlobe Juncture Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrEJ_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrEJ_C age group sumstats
TrEJ_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrEJ_C, na.rm = TRUE),
            max = max(TrEJ_C, na.rm = TRUE),
            mean = mean(TrEJ_C, na.rm = TRUE),
            sd = sd(TrEJ_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrEJ_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrEJ_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrEJ_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrEJ_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrEJ_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrEJ_C)))

TrEJ_Cage_sumstats <- TrEJ_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrEJ_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Earlobe Juncture Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrEJ_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrEJ_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Earlobe Juncture Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrEJ_C = "Subnasale/SubnasaleCont"))
```



TrGo_C  

```{r}
#TrGo_C race/eth sumstats
TrGo_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrGo_C, na.rm = TRUE),
            max = max(TrGo_C, na.rm = TRUE),
            mean = mean(TrGo_C, na.rm = TRUE),
            sd = sd(TrGo_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrGo_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrGo_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrGo_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrGo_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrGo_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrGo_C))) 

TrGo_Crace_sumstats <- TrGo_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrGo_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Gonion Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrGo_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrGo_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Gonion Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrGo_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrGo_C gender sumstats
TrGo_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrGo_C, na.rm = TRUE),
            max = max(TrGo_C, na.rm = TRUE),
            mean = mean(TrGo_C, na.rm = TRUE),
            sd = sd(TrGo_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrGo_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrGo_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrGo_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrGo_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrGo_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrGo_C)))

TrGo_Cgender_sumstats <- TrGo_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrGo_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Gonion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrGo_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrGo_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Gonion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrGo_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrGo_C age group sumstats
TrGo_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrGo_C, na.rm = TRUE),
            max = max(TrGo_C, na.rm = TRUE),
            mean = mean(TrGo_C, na.rm = TRUE),
            sd = sd(TrGo_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrGo_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrGo_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrGo_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrGo_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrGo_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrGo_C)))

TrGo_Cage_sumstats <- TrGo_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrGo_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Gonion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrGo_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrGo_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Gonion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrGo_C = "Subnasale/SubnasaleCont"))
```



TrSel_C  

```{r}
#TrSel_C race/eth sumstats
TrSel_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrSel_C, na.rm = TRUE),
            max = max(TrSel_C, na.rm = TRUE),
            mean = mean(TrSel_C, na.rm = TRUE),
            sd = sd(TrSel_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSel_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSel_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSel_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSel_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSel_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSel_C))) 

TrSel_Crace_sumstats <- TrSel_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrSel_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Sellion Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrSel_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSel_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Sellion Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSel_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrSel_C gender sumstats
TrSel_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrSel_C, na.rm = TRUE),
            max = max(TrSel_C, na.rm = TRUE),
            mean = mean(TrSel_C, na.rm = TRUE),
            sd = sd(TrSel_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSel_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSel_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSel_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSel_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSel_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSel_C)))

TrSel_Cgender_sumstats <- TrSel_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrSel_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Sellion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrSel_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSel_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Sellion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSel_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrSel_C age group sumstats
TrSel_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrSel_C, na.rm = TRUE),
            max = max(TrSel_C, na.rm = TRUE),
            mean = mean(TrSel_C, na.rm = TRUE),
            sd = sd(TrSel_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSel_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSel_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSel_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSel_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSel_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSel_C)))

TrSel_Cage_sumstats <- TrSel_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrSel_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Sellion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrSel_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSel_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Sellion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSel_C = "Subnasale/SubnasaleCont"))
```



TrSman_C  

```{r}
#TrSman_C race/eth sumstats
TrSman_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrSman_C, na.rm = TRUE),
            max = max(TrSman_C, na.rm = TRUE),
            mean = mean(TrSman_C, na.rm = TRUE),
            sd = sd(TrSman_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSman_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSman_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSman_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSman_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSman_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSman_C))) 

TrSman_Crace_sumstats <- TrSman_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrSman_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Submandibular Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrSman_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSman_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Submandibular Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSman_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrSman_C gender sumstats
TrSman_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrSman_C, na.rm = TRUE),
            max = max(TrSman_C, na.rm = TRUE),
            mean = mean(TrSman_C, na.rm = TRUE),
            sd = sd(TrSman_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSman_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSman_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSman_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSman_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSman_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSman_C)))

TrSman_Cgender_sumstats <- TrSman_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrSman_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Submandibular Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrSman_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSman_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Submandibular Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSman_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrSman_C age group sumstats
TrSman_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrSman_C, na.rm = TRUE),
            max = max(TrSman_C, na.rm = TRUE),
            mean = mean(TrSman_C, na.rm = TRUE),
            sd = sd(TrSman_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSman_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSman_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSman_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSman_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSman_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSman_C)))

TrSman_Cage_sumstats <- TrSman_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrSman_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Submandibular Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrSman_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSman_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Submandibular Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSman_C = "Subnasale/SubnasaleCont"))
```



TrSnas_C  

```{r}
#TrSnas_C race/eth sumstats
TrSnas_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrSnas_C, na.rm = TRUE),
            max = max(TrSnas_C, na.rm = TRUE),
            mean = mean(TrSnas_C, na.rm = TRUE),
            sd = sd(TrSnas_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSnas_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSnas_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSnas_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSnas_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSnas_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSnas_C))) 

TrSnas_Crace_sumstats <- TrSnas_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrSnas_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Subnasale Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrSnas_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSnas_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Subnasale Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSnas_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrSnas_C gender sumstats
TrSnas_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrSnas_C, na.rm = TRUE),
            max = max(TrSnas_C, na.rm = TRUE),
            mean = mean(TrSnas_C, na.rm = TRUE),
            sd = sd(TrSnas_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSnas_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSnas_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSnas_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSnas_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSnas_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSnas_C)))

TrSnas_Cgender_sumstats <- TrSnas_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrSnas_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Subnasale Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrSnas_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSnas_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Subnasale Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSnas_C = "Subnasale/SubnasaleCont"))
```

```{r}
#TrSnas_C age group sumstats
TrSnas_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrSnas_C, na.rm = TRUE),
            max = max(TrSnas_C, na.rm = TRUE),
            mean = mean(TrSnas_C, na.rm = TRUE),
            sd = sd(TrSnas_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrSnas_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrSnas_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrSnas_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrSnas_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrSnas_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrSnas_C)))

TrSnas_Cage_sumstats <- TrSnas_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrSnas_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Subnasale Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrSnas_C = "Subnasale/SubnasaleCont"))

#Autofit Width Table TNR
flextable(TrSnas_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Subnasale Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrSnas_C = "Subnasale/SubnasaleCont"))
```



TrTr_C  

```{r}
#TrTr_C race/eth sumstats
TrTr_Crace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrTr_C, na.rm = TRUE),
            max = max(TrTr_C, na.rm = TRUE),
            mean = mean(TrTr_C, na.rm = TRUE),
            sd = sd(TrTr_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrTr_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrTr_C))) 

TrTr_Crace_sumstats <- TrTr_Crace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrTr_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Contour SumStats by Race/Ethnicity") 
#%>% set_header_Cabels(values = list(TrTr_C = "Tragion/TragionCont"))

#Autofit Width Table TNR
flextable(TrTr_Crace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Contour SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrTr_C = "Tragion/TragionCont"))
```

```{r}
#TrTr_C gender sumstats
TrTr_Cgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrTr_C, na.rm = TRUE),
            max = max(TrTr_C, na.rm = TRUE),
            mean = mean(TrTr_C, na.rm = TRUE),
            sd = sd(TrTr_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrTr_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrTr_C)))

TrTr_Cgender_sumstats <- TrTr_Cgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrTr_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrTr_C = "Tragion/TragionCont"))

#Autofit Width Table TNR
flextable(TrTr_Cgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrTr_C = "Tragion/TragionCont"))
```

```{r}
#TrTr_C age group sumstats
TrTr_Cage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrTr_C, na.rm = TRUE),
            max = max(TrTr_C, na.rm = TRUE),
            mean = mean(TrTr_C, na.rm = TRUE),
            sd = sd(TrTr_C, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrTr_C, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_C, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_C, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_C, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_C, 0.95, na.rm=TRUE),
            na = sum(is.na(TrTr_C)))

TrTr_Cage_sumstats <- TrTr_Cage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrTr_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Contour SumStats by Gender") 
#%>% set_header_Cabels(values = list(TrTr_C = "Tragion/TragionCont"))

#Autofit Width Table TNR
flextable(TrTr_Cage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Contour SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Cabels(values = list(TrTr_C = "Tragion/TragionCont"))
```



TrTr_L  

```{r}
#TrTr_L race/eth sumstats
TrTr_Lrace_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(TrTr_L, na.rm = TRUE),
            max = max(TrTr_L, na.rm = TRUE),
            mean = mean(TrTr_L, na.rm = TRUE),
            sd = sd(TrTr_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrTr_L, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_L, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_L, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_L, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_L, 0.95, na.rm=TRUE),
            na = sum(is.na(TrTr_L))) 

TrTr_Lrace_sumstats <- TrTr_Lrace_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrTr_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Linear SumStats by Race/Ethnicity") 
#%>% set_header_Labels(values = list(TrTr_L = "Tragion/TragionCont"))

#Autofit Width Table TNR
flextable(TrTr_Lrace_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Linear SumStats by Race/Ethnicity") %>% 
  fit_to_width(7.5) 
#%>% set_header_Labels(values = list(TrTr_L = "Tragion/TragionCont"))
```

```{r}
#TrTr_L gender sumstats
TrTr_Lgender_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(TrTr_L, na.rm = TRUE),
            max = max(TrTr_L, na.rm = TRUE),
            mean = mean(TrTr_L, na.rm = TRUE),
            sd = sd(TrTr_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrTr_L, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_L, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_L, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_L, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_L, 0.95, na.rm=TRUE),
            na = sum(is.na(TrTr_L)))

TrTr_Lgender_sumstats <- TrTr_Lgender_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))

#Size 12 Table TNR
flextable(TrTr_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Linear SumStats by Gender") 
#%>% set_header_Labels(values = list(TrTr_L = "Tragion/TragionCont"))

#Autofit Width Table TNR
flextable(TrTr_Lgender_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Linear SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Labels(values = list(TrTr_L = "Tragion/TragionCont"))
```

```{r}
#TrTr_L age group sumstats
TrTr_Lage_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(TrTr_L, na.rm = TRUE),
            max = max(TrTr_L, na.rm = TRUE),
            mean = mean(TrTr_L, na.rm = TRUE),
            sd = sd(TrTr_L, na.rm = TRUE),
            se = sd/sqrt(n),
            percent5th = quantile(TrTr_L, 0.05, na.rm=TRUE),
            percent25th = quantile(TrTr_L, 0.25, na.rm=TRUE),
            percent50th = quantile(TrTr_L, 0.50, na.rm=TRUE),
            percent75th = quantile(TrTr_L, 0.75, na.rm=TRUE),
            percent95th = quantile(TrTr_L, 0.95, na.rm=TRUE),
            na = sum(is.na(TrTr_L)))

TrTr_Lage_sumstats <- TrTr_Lage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))


#Size 12 Table TNR
flextable(TrTr_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Linear SumStats by Gender") 
#%>% set_header_Labels(values = list(TrTr_L = "Tragion/TragionCont"))

#Autofit Width Table TNR
flextable(TrTr_Lage_sumstats) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Tragion to Tragion Linear SumStats by Gender") %>% 
  fit_to_width(7.5) 
#%>% set_header_Labels(values = list(TrTr_L = "Tragion/TragionCont"))
```



