---
title: "Untitled"
output:
  word_document: default
  html_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
library(officer)
library(flextable)
```
```{r}
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 11)
  ft
}
```


```{r}
load(file="headscan_full")
```


```{r}
age_sumstats <- headscan_full %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            quant5th = quantile(age, 0.05, na.rm=TRUE),
            quant25th = quantile(age, 0.25, na.rm=TRUE),
            quant50th = quantile(age, 0.50, na.rm=TRUE),
            quant75th = quantile(age, 0.75, na.rm=TRUE),
            quant95th = quantile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

age_sumstats <- age_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))
            
age_sumstats %>% 
  kbl(caption = "Age SumStats") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)
```

```{r}
flextable(age_sumstats) %>%
  my_ft_theme()
```


```{r}
raceage_sumstats <- headscan_full %>% 
  group_by(race_eth) %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            quant5th = quantile(age, 0.05, na.rm=TRUE),
            quant25th = quantile(age, 0.25, na.rm=TRUE),
            quant50th = quantile(age, 0.50, na.rm=TRUE),
            quant75th = quantile(age, 0.75, na.rm=TRUE),
            quant95th = quantile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

raceage_sumstats <- raceage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))
            
raceage_sumstats %>% 
  kbl(caption = "Age SumStats by Race/Ethnicity") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)
```

```{r}
genderage_sumstats <- headscan_full %>% 
  group_by(gender) %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            quant5th = quantile(age, 0.05, na.rm=TRUE),
            quant25th = quantile(age, 0.25, na.rm=TRUE),
            quant50th = quantile(age, 0.50, na.rm=TRUE),
            quant75th = quantile(age, 0.75, na.rm=TRUE),
            quant95th = quantile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

genderage_sumstats <- genderage_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))
            
genderage_sumstats %>% 
  kbl(caption = "Age SumStats by Gender") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)
```
```{r}
agegroup_sumstats <- headscan_full %>% 
  group_by(age_group) %>% 
  summarise(n = n(),
            min = min(age, na.rm = TRUE),
            max = max(age, na.rm = TRUE),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE),
            se = sd/sqrt(n),
            quant5th = quantile(age, 0.05, na.rm=TRUE),
            quant25th = quantile(age, 0.25, na.rm=TRUE),
            quant50th = quantile(age, 0.50, na.rm=TRUE),
            quant75th = quantile(age, 0.75, na.rm=TRUE),
            quant95th = quantile(age, 0.95, na.rm=TRUE),
            na = sum(is.na(age)))

agegroup_sumstats <- agegroup_sumstats %>% 
  mutate(across(where(is.numeric), round, 2))
            
agegroup_sumstats %>% 
  kbl(caption = "Age SumStats by Age Group") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE)
```