---
title: "levenes-test-manova"
output: html_document
date: "2022-09-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
library(flextable)
library(extrafont)
library(writexl)
library(car)
```

```{r}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```


```{r}
SA3_noout <- read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chosen_nona1.xlsx")
```

Levene's test, no transformation

```{r}

AA_C_levene <- leveneTest(AA_C ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
AA_C_levene <- rownames_to_column(AA_C_levene, "X")
AA_C_levene$measure <-"AA_C"
AA_C_levene <- AA_C_levene[-c(1)]
AA_C_levene <- AA_C_levene[-c(2),]


BiW_C_levene <- leveneTest(BiW_C ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_C_levene <- rownames_to_column(BiW_C_levene, "X")
BiW_C_levene$measure <-"BiW_C"
BiW_C_levene <- BiW_C_levene[-c(1)]
BiW_C_levene <- BiW_C_levene[-c(2),]


BiW_L_levene <- leveneTest(BiW_L ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_L_levene <- rownames_to_column(BiW_L_levene, "X")
BiW_L_levene$measure <-"BiW_L"
BiW_L_levene <- BiW_L_levene[-c(1)]
BiW_L_levene <- BiW_L_levene[-c(2),]


GoSub_C_levene <- leveneTest(GoSub_C ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
GoSub_C_levene <- rownames_to_column(GoSub_C_levene, "X")
GoSub_C_levene$measure <-"GoSub_C"
GoSub_C_levene <- GoSub_C_levene[-c(1)]
GoSub_C_levene <- GoSub_C_levene[-c(2),]


NRB_L_levene <- leveneTest(NRB_L ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
NRB_L_levene <- rownames_to_column(NRB_L_levene, "X")
NRB_L_levene$measure <-"NRB_L"
NRB_L_levene <- NRB_L_levene[-c(1)]
NRB_L_levene <- NRB_L_levene[-c(2),]


ProS_L_levene <- leveneTest(ProS_L ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
ProS_L_levene <- rownames_to_column(ProS_L_levene, "X")
ProS_L_levene$measure <-"ProS_L"
ProS_L_levene <- ProS_L_levene[-c(1)]
ProS_L_levene <- ProS_L_levene[-c(2),]


SelP_L_levene <- leveneTest(SelP_L ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelP_L_levene <- rownames_to_column(SelP_L_levene, "X")
SelP_L_levene$measure <-"SelP_L"
SelP_L_levene <- SelP_L_levene[-c(1)]
SelP_L_levene <- SelP_L_levene[-c(2),]


SelM_L_levene <- leveneTest(SelM_L ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelM_L_levene <- rownames_to_column(SelM_L_levene, "X")
SelM_L_levene$measure <-"SelM_L"
SelM_L_levene <- SelM_L_levene[-c(1)]
SelM_L_levene <- SelM_L_levene[-c(2),]


SnasM_C_levene <- leveneTest(SnasM_C ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SnasM_C_levene <- rownames_to_column(SnasM_C_levene, "X")
SnasM_C_levene$measure <-"SnasM_C"
SnasM_C_levene <- SnasM_C_levene[-c(1)]
SnasM_C_levene <- SnasM_C_levene[-c(2),]


TrSman_C_levene <- leveneTest(TrSman_C ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrSman_C_levene <- rownames_to_column(TrSman_C_levene, "X")
TrSman_C_levene$measure <-"TrSman_C"
TrSman_C_levene <- TrSman_C_levene[-c(1)]
TrSman_C_levene <- TrSman_C_levene[-c(2),]


TrTr_C_levene <- leveneTest(TrTr_C ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_C_levene <- rownames_to_column(TrTr_C_levene, "X")
TrTr_C_levene$measure <-"TrTr_C"
TrTr_C_levene <- TrTr_C_levene[-c(1)]
TrTr_C_levene <- TrTr_C_levene[-c(2),]


TrTr_L_levene <- leveneTest(TrTr_L ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_L_levene <- rownames_to_column(TrTr_L_levene, "X")
TrTr_L_levene$measure <-"TrTr_L"
TrTr_L_levene <- TrTr_L_levene[-c(1)]
TrTr_L_levene <- TrTr_L_levene[-c(2),]

levene_data <- rbind(AA_C_levene, BiW_C_levene, BiW_L_levene, GoSub_C_levene, NRB_L_levene,
                     ProS_L_levene, SelP_L_levene, SelM_L_levene, SnasM_C_levene,
                     TrSman_C_levene, TrTr_C_levene, TrTr_L_levene)

levene_data <- levene_data[c(4,1,2,3)]

levene_data$p_val <- levene_data$`Pr(>F)`

levene_data$equal_var <- with(levene_data, ifelse(p_val < 0.05, 'FALSE', 'TRUE'))

levene_data <- levene_data[-c(5)]
```

```{r}
#Size 12 Table TNR
flextable(levene_data) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(levene_data) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```



Levene's test, log base 10 transformation
```{r}

AA_C_levene10 <- leveneTest(log(AA_C , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
AA_C_levene10 <- rownames_to_column(AA_C_levene10, "X")
AA_C_levene10$measure <-"AA_C"
AA_C_levene10 <- AA_C_levene10[-c(1)]
AA_C_levene10 <- AA_C_levene10[-c(2),]


BiW_C_levene10 <- leveneTest(log(BiW_C , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_C_levene10 <- rownames_to_column(BiW_C_levene10, "X")
BiW_C_levene10$measure <-"BiW_C"
BiW_C_levene10 <- BiW_C_levene10[-c(1)]
BiW_C_levene10 <- BiW_C_levene10[-c(2),]


BiW_L_levene10 <- leveneTest(log(BiW_L , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_L_levene10 <- rownames_to_column(BiW_L_levene10, "X")
BiW_L_levene10$measure <-"BiW_L"
BiW_L_levene10 <- BiW_L_levene10[-c(1)]
BiW_L_levene10 <- BiW_L_levene10[-c(2),]


GoSub_C_levene10 <- leveneTest(log(GoSub_C , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
GoSub_C_levene10 <- rownames_to_column(GoSub_C_levene10, "X")
GoSub_C_levene10$measure <-"GoSub_C"
GoSub_C_levene10 <- GoSub_C_levene10[-c(1)]
GoSub_C_levene10 <- GoSub_C_levene10[-c(2),]


NRB_L_levene10 <- leveneTest(log(NRB_L , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
NRB_L_levene10 <- rownames_to_column(NRB_L_levene10, "X")
NRB_L_levene10$measure <-"NRB_L"
NRB_L_levene10 <- NRB_L_levene10[-c(1)]
NRB_L_levene10 <- NRB_L_levene10[-c(2),]


ProS_L_levene10 <- leveneTest(log(ProS_L , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
ProS_L_levene10 <- rownames_to_column(ProS_L_levene10, "X")
ProS_L_levene10$measure <-"ProS_L"
ProS_L_levene10 <- ProS_L_levene10[-c(1)]
ProS_L_levene10 <- ProS_L_levene10[-c(2),]


SelP_L_levene10 <- leveneTest(log(SelP_L , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelP_L_levene10 <- rownames_to_column(SelP_L_levene10, "X")
SelP_L_levene10$measure <-"SelP_L"
SelP_L_levene10 <- SelP_L_levene10[-c(1)]
SelP_L_levene10 <- SelP_L_levene10[-c(2),]


SelM_L_levene10 <- leveneTest(log(SelM_L , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelM_L_levene10 <- rownames_to_column(SelM_L_levene10, "X")
SelM_L_levene10$measure <-"SelM_L"
SelM_L_levene10 <- SelM_L_levene10[-c(1)]
SelM_L_levene10 <- SelM_L_levene10[-c(2),]


SnasM_C_levene10 <- leveneTest(log(SnasM_C , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SnasM_C_levene10 <- rownames_to_column(SnasM_C_levene10, "X")
SnasM_C_levene10$measure <-"SnasM_C"
SnasM_C_levene10 <- SnasM_C_levene10[-c(1)]
SnasM_C_levene10 <- SnasM_C_levene10[-c(2),]


TrSman_C_levene10 <- leveneTest(log(TrSman_C , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrSman_C_levene10 <- rownames_to_column(TrSman_C_levene10, "X")
TrSman_C_levene10$measure <-"TrSman_C"
TrSman_C_levene10 <- TrSman_C_levene10[-c(1)]
TrSman_C_levene10 <- TrSman_C_levene10[-c(2),]


TrTr_C_levene10 <- leveneTest(log(TrTr_C , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_C_levene10 <- rownames_to_column(TrTr_C_levene10, "X")
TrTr_C_levene10$measure <-"TrTr_C"
TrTr_C_levene10 <- TrTr_C_levene10[-c(1)]
TrTr_C_levene10 <- TrTr_C_levene10[-c(2),]


TrTr_L_levene10 <- leveneTest(log(TrTr_L , base=10) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_L_levene10 <- rownames_to_column(TrTr_L_levene10, "X")
TrTr_L_levene10$measure <-"TrTr_L"
TrTr_L_levene10 <- TrTr_L_levene10[-c(1)]
TrTr_L_levene10 <- TrTr_L_levene10[-c(2),]

levene_data10 <- rbind(AA_C_levene10, BiW_C_levene10, BiW_L_levene10, GoSub_C_levene10, NRB_L_levene10,
                     ProS_L_levene10, SelP_L_levene10, SelM_L_levene10, SnasM_C_levene10,
                     TrSman_C_levene10, TrTr_C_levene10, TrTr_L_levene10)

levene_data10 <- levene_data10[c(4,1,2,3)]

levene_data10$p_val <- levene_data10$`Pr(>F)`

levene_data10$equal_var <- with(levene_data10, ifelse(p_val < 0.05, 'FALSE', 'TRUE'))

levene_data10 <- levene_data10[-c(5)]
```


```{r}
#Size 12 Table TNR
flextable(levene_data10) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values, Log Base 10 Transformation") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(levene_data10) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values, Log Base 10 Transformation") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```




Levene's test, log transformation

```{r}

AA_C_levene_e <- leveneTest(log(AA_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
AA_C_levene_e <- rownames_to_column(AA_C_levene_e, "X")
AA_C_levene_e$measure <-"AA_C"
AA_C_levene_e <- AA_C_levene_e[-c(1)]
AA_C_levene_e <- AA_C_levene_e[-c(2),]


BiW_C_levene_e <- leveneTest(log(BiW_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_C_levene_e <- rownames_to_column(BiW_C_levene_e, "X")
BiW_C_levene_e$measure <-"BiW_C"
BiW_C_levene_e <- BiW_C_levene_e[-c(1)]
BiW_C_levene_e <- BiW_C_levene_e[-c(2),]


BiW_L_levene_e <- leveneTest(log(BiW_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_L_levene_e <- rownames_to_column(BiW_L_levene_e, "X")
BiW_L_levene_e$measure <-"BiW_L"
BiW_L_levene_e <- BiW_L_levene_e[-c(1)]
BiW_L_levene_e <- BiW_L_levene_e[-c(2),]


GoSub_C_levene_e <- leveneTest(log(GoSub_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
GoSub_C_levene_e <- rownames_to_column(GoSub_C_levene_e, "X")
GoSub_C_levene_e$measure <-"GoSub_C"
GoSub_C_levene_e <- GoSub_C_levene_e[-c(1)]
GoSub_C_levene_e <- GoSub_C_levene_e[-c(2),]


NRB_L_levene_e <- leveneTest(log(NRB_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
NRB_L_levene_e <- rownames_to_column(NRB_L_levene_e, "X")
NRB_L_levene_e$measure <-"NRB_L"
NRB_L_levene_e <- NRB_L_levene_e[-c(1)]
NRB_L_levene_e <- NRB_L_levene_e[-c(2),]


ProS_L_levene_e <- leveneTest(log(ProS_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
ProS_L_levene_e <- rownames_to_column(ProS_L_levene_e, "X")
ProS_L_levene_e$measure <-"ProS_L"
ProS_L_levene_e <- ProS_L_levene_e[-c(1)]
ProS_L_levene_e <- ProS_L_levene_e[-c(2),]


SelP_L_levene_e <- leveneTest(log(SelP_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelP_L_levene_e <- rownames_to_column(SelP_L_levene_e, "X")
SelP_L_levene_e$measure <-"SelP_L"
SelP_L_levene_e <- SelP_L_levene_e[-c(1)]
SelP_L_levene_e <- SelP_L_levene_e[-c(2),]


SelM_L_levene_e <- leveneTest(log(SelM_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelM_L_levene_e <- rownames_to_column(SelM_L_levene_e, "X")
SelM_L_levene_e$measure <-"SelM_L"
SelM_L_levene_e <- SelM_L_levene_e[-c(1)]
SelM_L_levene_e <- SelM_L_levene_e[-c(2),]


SnasM_C_levene_e <- leveneTest(log(SnasM_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SnasM_C_levene_e <- rownames_to_column(SnasM_C_levene_e, "X")
SnasM_C_levene_e$measure <-"SnasM_C"
SnasM_C_levene_e <- SnasM_C_levene_e[-c(1)]
SnasM_C_levene_e <- SnasM_C_levene_e[-c(2),]


TrSman_C_levene_e <- leveneTest(log(TrSman_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrSman_C_levene_e <- rownames_to_column(TrSman_C_levene_e, "X")
TrSman_C_levene_e$measure <-"TrSman_C"
TrSman_C_levene_e <- TrSman_C_levene_e[-c(1)]
TrSman_C_levene_e <- TrSman_C_levene_e[-c(2),]


TrTr_C_levene_e <- leveneTest(log(TrTr_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_C_levene_e <- rownames_to_column(TrTr_C_levene_e, "X")
TrTr_C_levene_e$measure <-"TrTr_C"
TrTr_C_levene_e <- TrTr_C_levene_e[-c(1)]
TrTr_C_levene_e <- TrTr_C_levene_e[-c(2),]


TrTr_L_levene_e <- leveneTest(log(TrTr_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_L_levene_e <- rownames_to_column(TrTr_L_levene_e, "X")
TrTr_L_levene_e$measure <-"TrTr_L"
TrTr_L_levene_e <- TrTr_L_levene_e[-c(1)]
TrTr_L_levene_e <- TrTr_L_levene_e[-c(2),]

levene_data_e <- rbind(AA_C_levene_e, BiW_C_levene_e, BiW_L_levene_e, GoSub_C_levene_e, NRB_L_levene_e,
                     ProS_L_levene_e, SelP_L_levene_e, SelM_L_levene_e, SnasM_C_levene_e,
                     TrSman_C_levene_e, TrTr_C_levene_e, TrTr_L_levene_e)

levene_data_e <- levene_data_e[c(4,1,2,3)]

levene_data_e$p_val <- levene_data_e$`Pr(>F)`

levene_data_e$equal_var <- with(levene_data_e, ifelse(p_val < 0.05, 'FALSE', 'TRUE'))

levene_data_e <- levene_data_e[-c(5)]
```

```{r}
#Size 12 Table TNR
flextable(levene_data_e) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values, Log e Transformation") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(levene_data_e) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values, Log e Transformation") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```





Levene's test, sqrt transformation

```{r}

AA_C_levenesqrt <- leveneTest(sqrt(AA_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
AA_C_levenesqrt <- rownames_to_column(AA_C_levenesqrt, "X")
AA_C_levenesqrt$measure <-"AA_C"
AA_C_levenesqrt <- AA_C_levenesqrt[-c(1)]
AA_C_levenesqrt <- AA_C_levenesqrt[-c(2),]


BiW_C_levenesqrt <- leveneTest(sqrt(BiW_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_C_levenesqrt <- rownames_to_column(BiW_C_levenesqrt, "X")
BiW_C_levenesqrt$measure <-"BiW_C"
BiW_C_levenesqrt <- BiW_C_levenesqrt[-c(1)]
BiW_C_levenesqrt <- BiW_C_levenesqrt[-c(2),]


BiW_L_levenesqrt <- leveneTest(sqrt(BiW_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
BiW_L_levenesqrt <- rownames_to_column(BiW_L_levenesqrt, "X")
BiW_L_levenesqrt$measure <-"BiW_L"
BiW_L_levenesqrt <- BiW_L_levenesqrt[-c(1)]
BiW_L_levenesqrt <- BiW_L_levenesqrt[-c(2),]


GoSub_C_levenesqrt <- leveneTest(sqrt(GoSub_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
GoSub_C_levenesqrt <- rownames_to_column(GoSub_C_levenesqrt, "X")
GoSub_C_levenesqrt$measure <-"GoSub_C"
GoSub_C_levenesqrt <- GoSub_C_levenesqrt[-c(1)]
GoSub_C_levenesqrt <- GoSub_C_levenesqrt[-c(2),]


NRB_L_levenesqrt <- leveneTest(sqrt(NRB_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
NRB_L_levenesqrt <- rownames_to_column(NRB_L_levenesqrt, "X")
NRB_L_levenesqrt$measure <-"NRB_L"
NRB_L_levenesqrt <- NRB_L_levenesqrt[-c(1)]
NRB_L_levenesqrt <- NRB_L_levenesqrt[-c(2),]


ProS_L_levenesqrt <- leveneTest(sqrt(ProS_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
ProS_L_levenesqrt <- rownames_to_column(ProS_L_levenesqrt, "X")
ProS_L_levenesqrt$measure <-"ProS_L"
ProS_L_levenesqrt <- ProS_L_levenesqrt[-c(1)]
ProS_L_levenesqrt <- ProS_L_levenesqrt[-c(2),]


SelP_L_levenesqrt <- leveneTest(sqrt(SelP_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelP_L_levenesqrt <- rownames_to_column(SelP_L_levenesqrt, "X")
SelP_L_levenesqrt$measure <-"SelP_L"
SelP_L_levenesqrt <- SelP_L_levenesqrt[-c(1)]
SelP_L_levenesqrt <- SelP_L_levenesqrt[-c(2),]


SelM_L_levenesqrt <- leveneTest(sqrt(SelM_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SelM_L_levenesqrt <- rownames_to_column(SelM_L_levenesqrt, "X")
SelM_L_levenesqrt$measure <-"SelM_L"
SelM_L_levenesqrt <- SelM_L_levenesqrt[-c(1)]
SelM_L_levenesqrt <- SelM_L_levenesqrt[-c(2),]


SnasM_C_levenesqrt <- leveneTest(sqrt(SnasM_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
SnasM_C_levenesqrt <- rownames_to_column(SnasM_C_levenesqrt, "X")
SnasM_C_levenesqrt$measure <-"SnasM_C"
SnasM_C_levenesqrt <- SnasM_C_levenesqrt[-c(1)]
SnasM_C_levenesqrt <- SnasM_C_levenesqrt[-c(2),]


TrSman_C_levenesqrt <- leveneTest(sqrt(TrSman_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrSman_C_levenesqrt <- rownames_to_column(TrSman_C_levenesqrt, "X")
TrSman_C_levenesqrt$measure <-"TrSman_C"
TrSman_C_levenesqrt <- TrSman_C_levenesqrt[-c(1)]
TrSman_C_levenesqrt <- TrSman_C_levenesqrt[-c(2),]


TrTr_C_levenesqrt <- leveneTest(sqrt(TrTr_C) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_C_levenesqrt <- rownames_to_column(TrTr_C_levenesqrt, "X")
TrTr_C_levenesqrt$measure <-"TrTr_C"
TrTr_C_levenesqrt <- TrTr_C_levenesqrt[-c(1)]
TrTr_C_levenesqrt <- TrTr_C_levenesqrt[-c(2),]


TrTr_L_levenesqrt <- leveneTest(sqrt(TrTr_L) ~ gender+race_eth+age_group, data=SA3_noout, center=mean)
TrTr_L_levenesqrt <- rownames_to_column(TrTr_L_levenesqrt, "X")
TrTr_L_levenesqrt$measure <-"TrTr_L"
TrTr_L_levenesqrt <- TrTr_L_levenesqrt[-c(1)]
TrTr_L_levenesqrt <- TrTr_L_levenesqrt[-c(2),]

levene_datasqrt <- rbind(AA_C_levenesqrt, BiW_C_levenesqrt, BiW_L_levenesqrt, GoSub_C_levenesqrt, NRB_L_levenesqrt,
                     ProS_L_levenesqrt, SelP_L_levenesqrt, SelM_L_levenesqrt, SnasM_C_levenesqrt,
                     TrSman_C_levenesqrt, TrTr_C_levenesqrt, TrTr_L_levenesqrt)

levene_datasqrt <- levene_datasqrt[c(4,1,2,3)]

levene_datasqrt$p_val <- levene_datasqrt$`Pr(>F)`

levene_datasqrt$equal_var <- with(levene_datasqrt, ifelse(p_val < 0.05, 'FALSE', 'TRUE'))

levene_datasqrt <- levene_datasqrt[-c(5)]
```

```{r}
#Size 12 Table TNR
flextable(levene_datasqrt) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values, Square Root Transformation") 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))

#Autofit Width Table TNR
flextable(levene_datasqrt) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Levene's Test Values, Square Root Transformation") %>% 
  fit_to_width(7.5) 
#%>% set_header_labels(values = list(AA_C = "Alare/AlareCont"))
```




