---
title: "exploring-demo-postimpute"
output:
  word_document: default
  html_document: default
date: "2022-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(readxl)
library(flextable)
library(extrafont)
library(forcats)
```

```{r table-function}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}
chosen_withna<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chosen_withna.xlsx")

chosen_withna$gender<-as.factor(chosen_withna$gender)
chosen_withna$race_eth<-as.factor(chosen_withna$race_eth)
chosen_withna$age_group<-as.factor(chosen_withna$age_group)


str(chosen_withna)
```




```{r}
chosen_withna %>% 
  ggplot(aes(x=fct_infreq(race_eth), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Race/Ethnicity Frequency",
       subtitle="With NA values and all demographics retained",
       y="Count",
       x="Race/Ethnicity")
```



```{r}
chosen_withna %>% 
  ggplot(aes(x=fct_infreq(gender), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Gender Frequency",
       subtitle="With NA values and all demographics retained",
       y="Count",
       x="Gender")
```



```{r}
chosen_withna %>% 
  ggplot(aes(x=fct_infreq(age_group), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Age Group Frequency",
       subtitle="With NA values and all demographics retained",
       y="Count",
       x="Age Group")
```


```{r}
chosen_nona<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chosen_nona.xlsx")

chosen_nona$gender<-as.factor(chosen_nona$gender)
chosen_nona$race_eth<-as.factor(chosen_nona$race_eth)
chosen_nona$age_group<-as.factor(chosen_nona$age_group)


str(chosen_nona)
```




```{r}
chosen_nona %>% 
  ggplot(aes(x=fct_infreq(race_eth), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Race/Ethnicity Frequency",
       subtitle="With NA values removed and all demographics retained",
       y="Count",
       x="Race/Ethnicity")
```



```{r}
chosen_nona %>% 
  ggplot(aes(x=fct_infreq(gender), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Gender Frequency",
       subtitle="With NA values removed and all demographics retained",
       y="Count",
       x="Gender")
```



```{r}
chosen_nona %>% 
  ggplot(aes(x=fct_infreq(age_group), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Age Group Frequency",
       subtitle="With NA values removed and all demographics retained",
       y="Count",
       x="Age Group")
```



```{r}
chosen_imputed<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chosen_imputed.xlsx")

chosen_imputed$gender<-as.factor(chosen_imputed$gender)
chosen_imputed$race_eth<-as.factor(chosen_imputed$race_eth)
chosen_imputed$age_group<-as.factor(chosen_imputed$age_group)


str(chosen_imputed)
```




```{r}
chosen_imputed %>% 
  ggplot(aes(x=fct_infreq(race_eth), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Race/Ethnicity Frequency",
       subtitle="With NA values imputed and all demographics retained",
       y="Count",
       x="Race/Ethnicity")
```



```{r}
chosen_imputed %>% 
  ggplot(aes(x=fct_infreq(gender), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Gender Frequency",
       subtitle="With NA values imputed and all demographics retained",
       y="Count",
       x="Gender")
```



```{r}
chosen_imputed %>% 
  ggplot(aes(x=fct_infreq(age_group), label=scales::percent(prop.table(stat(count)))))+
  geom_bar(stat="count", color= "black", fill = "white")+
  geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  labs(title="Age Group Frequency",
       subtitle="With NA values imputed and all demographics retained",
       y="Count",
       x="Age Group")
```