---
title: "PCA-imputed"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(flextable)
library(readxl)
library(extrafont)
#library(forcats)
library(writexl)
library(ggfortify) #autoplot
library(scales) #percent()
```

```{r table-function}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r}
#PCAdata_num <- PCAdata_num %>% drop_na()
PCAdata_full<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chosen_imputed.xlsx")



PCAdata_num <- select_if(PCAdata_full, is.numeric)

str(PCAdata_num)
```


```{r}
#https://www.statology.org/principal-components-analysis-in-r/

#calculate principal components
pca_res <- prcomp(PCAdata_num, scale=TRUE)

#reverse the signs (R calculates eigenvectors in negative direction)
pca_res$rotation <- -1*pca_res$rotation

#display PCs
pca_res$rotation
```


```{r}
var_explained = pca_res$sdev^2 / sum(pca_res$sdev^2)

var_explained_total <- var_explained
```




```{r, fig.width=5, fig.height=4}
qplot(c(1:12), var_explained) + 
  geom_line() + 
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  xlab("Principal Component") + 
  ylab("Variance Explained (proportion)") +
  ggtitle("Scree Plot: Imputed Data") +
  ylim(0, 1) +
  scale_x_discrete(limits=c("PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10","PC11","PC12")) 
```


```{r}
var_explained_data <- data.frame(var_explained)

var_explained_data <- var_explained_data %>% 
  rename(v_e = "var_explained")


var_explained_data$vep <- var_explained_data$v_e

var_explained_data <- rownames_to_column(var_explained_data, "PC_num")

var_explained_data$vep <- percent(var_explained_data$vep, accuracy=0.01)

var_explained_data$PC_num <- as.factor(var_explained_data$PC_num)

var_explained_data$PC_num <- 
  recode_factor(var_explained_data$PC_num, 
                '1'= "PC1",
                '2'= "PC2",
                '3'= "PC3",
                '4'= "PC4",
                '5'= "PC5",
                '6'= "PC6",
                '7'= "PC7",
                '8'= "PC8",
                '9'= "PC9",
                '10'= "PC10",
                '11'= "PC11",
                '12'= "PC12")
```

```{r}
ggplot(data=var_explained_data, aes(x=PC_num, y=v_e, group=1)) + 
  geom_line() +
  geom_point() + 
  geom_text(aes(label=vep),
            position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank() 
        )+
  labs(title="Scree Plot: Imputed Data",
       x="Principal Component",
       y="Total Variance Explained")
```


```{r}

#making plot axis match the ggplot versions in PCA2.Rmd!!! 
#compare to PCAdata_full1 pc1 and pc2 columns (should be same sign, here times 100)
pca_res$x <- pca_res$x * 100
pca_res$x[,1] <- pca_res$x[,1] * -1
#pca_res$x <- pca_res$x[,2] * 100

#pca_res$x
```


#https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html

```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full)+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+  
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title="PCA Plot: Imputed Data")
```


```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full, colour="race_eth")+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman")) +
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Race/Ethnicities PCA Plot: Imputed Data",
       color = "Race/Ethnicity")
```
```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full, colour="race_eth",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Race/Ethnicities PCA Plot: Imputed Data",
       subtitle = "with factor loadings",
       color = "Race/Ethnicity")
```
arrows close together=higher correlation

COULD add ellipses (like in PCA2) to this graph with factor loadings.. 
but cannot add loadings to plot in PCA2 with ellipses 


```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full, colour="gender")+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Genders PCA Plot: Imputed Data",
       color = "Gender")
```

```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full, colour="gender",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Genders PCA Plot: Imputed Data",
       subtitle = "with factor loadings",
       color = "Gender")
```


```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full, colour="age_group")+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Age Groups PCA Plot: Imputed Data",
       color = "Age Group")
```


```{r, fig.width=8, fig.height=5}
autoplot(pca_res, data=PCAdata_full, colour="age_group",
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)+
  geom_hline(yintercept = 0, lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  theme_bw() + theme(text=element_text(family= "Times New Roman"))+
  labs(y="PC2 (18.83%)",
       x="PC1 (38.4%)",
       title = "All Age Groups PCA Plot: Imputed Data",
       subtitle = "with factor loadings",
       color = "Age Group")
```



